version: "2"
services:
  web:
    image: meanbee/magento:5.6-apache
    hostname: magento-dev.docker
    ports:
      - 8080:80
    volumes_from:
      - appdata
    environment:
      - VIRTUAL_HOST=magento-dev.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
      - ENABLE_SENDMAIL=true
      - XDEBUG_CONFIG=remote_host=172.17.0.1 idekey=PHPSTORM remote_enable=On remote_autostart=On
    links:
      - db

  cron:
    image: meanbee/magento:5.6-cli
    hostname: cron.magento-dev.docker
    working_dir: /var/www/html
    command: /run-cron.sh
    volumes_from:
      - appdata
    environment:
      - ENABLE_SENDMAIL=true
    links:
      - db

  cli:
    image: meanbee/magento:5.6-cli
    hostname: cli.magento-dev.docker
    working_dir: /var/www/html
    command: /bin/true
    volumes_from:
      - appdata
    environment:
      - AWS_ACCESS_KEY_ID=00000000000000000000
      - AWS_SECRET_ACCESS_KEY=0000000000000000000000000000000000000000
      - AWS_REGION=eu-west-1
      - AWS_BUCKET=magedbm
      - AWS_MEDIA_BUCKET=magemm
    links:
      - db

  db:
    image: meanbee/magento-mysql
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_DATABASE=magento
    volumes:
      - ./mysql/data:/var/lib/mysql
  appdata:
    image: tianon/true
    volumes:
      - .:/var/www/html

  redis:
    image: redis:3.2.8
    ports:
     - 6379:6379
    volumes:
          - /redis:/data
  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"