<?php $this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('page/1column.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'lib/ccard.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'scriptaculous/controls.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'scriptaculous/builder.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'scriptaculous/dragdrop.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'scriptaculous/controls.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'scriptaculous/slider.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'varien/js.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'varien/menu.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('top.links'));
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('top.search'));
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('top.menu'));
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('footer'));