<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Include('customer_account'));
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_info', 'as' => 'info', 'name' => 'sales.order.info'), 'sales.order.info', 'my.account.wrapper', array()), false);
$this->addItemRelation($item, 'sales.order.info');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_info_buttons', 'as' => 'buttons', 'name' => 'sales.order.info.buttons'), 'sales.order.info.buttons', 'sales.order.info', array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'sales.order.info.buttons');
$this->addItemRelation($item, 'sales.order.info');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_creditmemo', 'name' => 'sales.order.creditmemo'), 'sales.order.creditmemo', 'my.account.wrapper', array()), false);
$this->addItemRelation($item, 'sales.order.creditmemo');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_creditmemo_items', 'name' => 'creditmemo_items', 'template' => 'sales/order/creditmemo/items.phtml'), 'creditmemo_items', 'sales.order.creditmemo', array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'creditmemo_items');
$this->addItemRelation($item, 'sales.order.creditmemo');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'creditmemo_items', function ($block) { return $block->addItemRender('default', 'sales/order_item_renderer_default', 'sales/order/creditmemo/items/renderer/default.phtml'); }, array(0 => 'my.account.wrapper', 1 => 'sales.order.creditmemo')), false);
$this->addItemRelation($item, 'creditmemo_items');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.order.creditmemo');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'creditmemo_items', function ($block) { return $block->addItemRender('grouped', 'sales/order_item_renderer_grouped', 'sales/order/creditmemo/items/renderer/default.phtml'); }, array(0 => 'my.account.wrapper', 1 => 'sales.order.creditmemo')), false);
$this->addItemRelation($item, 'creditmemo_items');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.order.creditmemo');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_creditmemo_totals', 'name' => 'creditmemo_totals', 'template' => 'sales/order/totals.phtml'), 'creditmemo_totals', 'creditmemo_items', array(0 => 'my.account.wrapper', 1 => 'sales.order.creditmemo')), false);
$this->addItemRelation($item, 'creditmemo_totals');
$this->addItemRelation($item, 'creditmemo_items');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.order.creditmemo');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setLabelProperties'), 'creditmemo_totals', function ($block) { return $block->setLabelProperties('colspan="6" class="a-right"'); }, array(0 => 'my.account.wrapper', 1 => 'sales.order.creditmemo', 2 => 'creditmemo_items')), false);
$this->addItemRelation($item, 'creditmemo_totals');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.order.creditmemo');
$this->addItemRelation($item, 'creditmemo_items');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setValueProperties'), 'creditmemo_totals', function ($block) { return $block->setValueProperties('class="a-right"'); }, array(0 => 'my.account.wrapper', 1 => 'sales.order.creditmemo', 2 => 'creditmemo_items')), false);
$this->addItemRelation($item, 'creditmemo_totals');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.order.creditmemo');
$this->addItemRelation($item, 'creditmemo_items');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'tax/sales_order_tax', 'name' => 'tax', 'template' => 'tax/order/tax.phtml'), 'tax', 'creditmemo_totals', array(0 => 'my.account.wrapper', 1 => 'sales.order.creditmemo', 2 => 'creditmemo_items')), false);
$this->addItemRelation($item, 'tax');
$this->addItemRelation($item, 'creditmemo_totals');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.order.creditmemo');
$this->addItemRelation($item, 'creditmemo_items');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_comments', 'name' => 'creditmemo_comments', 'template' => 'sales/order/comments.phtml'), 'creditmemo_comments', 'creditmemo_items', array(0 => 'my.account.wrapper', 1 => 'sales.order.creditmemo')), false);
$this->addItemRelation($item, 'creditmemo_comments');
$this->addItemRelation($item, 'creditmemo_items');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.order.creditmemo');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addLink', 'translate' => 'label', 'module' => 'sales'), 'sales.order.info', function ($block) { return $block->addLink('view', '*/*/view', Mage::helper('sales')->__('Order Information')); }, array()), false);
$this->addItemRelation($item, 'sales.order.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addLink', 'translate' => 'label', 'module' => 'sales'), 'sales.order.info', function ($block) { return $block->addLink('invoice', '*/*/invoice', Mage::helper('sales')->__('Invoices')); }, array()), false);
$this->addItemRelation($item, 'sales.order.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addLink', 'translate' => 'label', 'module' => 'sales'), 'sales.order.info', function ($block) { return $block->addLink('shipment', '*/*/shipment', Mage::helper('sales')->__('Shipments')); }, array()), false);
$this->addItemRelation($item, 'sales.order.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addLink', 'translate' => 'label', 'module' => 'sales'), 'sales.order.info', function ($block) { return $block->addLink('creditmemo', '', Mage::helper('sales')->__('Refunds')); }, array()), false);
$this->addItemRelation($item, 'sales.order.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'additional.product.info'), 'additional.product.info', null, array()), false);
$this->addItemRelation($item, 'additional.product.info');
$this->addItemRelation($item, NULL);