<?php $this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addNotice', 'translate' => 'message'), 'messages', function ($block) { return $block->addNotice(Mage::helper('core')->__('This report depends on timezone configuration. Once timezone is changed, the lifetime statistics need to be refreshed.')); }, array()), false);
$this->addItemRelation($item, 'messages');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/report_product_viewed', 'template' => 'report/grid/container.phtml', 'name' => 'product.report.grid.container'), 'product.report.grid.container', 'content', array()), false);
$this->addItemRelation($item, 'product.report.grid.container');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/store_switcher', 'template' => 'report/store/switcher/enhanced.phtml', 'name' => 'store.switcher'), 'store.switcher', 'product.report.grid.container', array(0 => 'content')), false);
$this->addItemRelation($item, 'store.switcher');
$this->addItemRelation($item, 'product.report.grid.container');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setStoreVarName'), 'store.switcher', function ($block) { return $block->setStoreVarName('store_ids'); }, array(0 => 'content', 1 => 'product.report.grid.container')), false);
$this->addItemRelation($item, 'store.switcher');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'product.report.grid.container');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/report_filter_form', 'name' => 'grid.filter.form'), 'grid.filter.form', 'product.report.grid.container', array(0 => 'content')), false);
$this->addItemRelation($item, 'grid.filter.form');
$this->addItemRelation($item, 'product.report.grid.container');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setFieldVisibility'), 'grid.filter.form', function ($block) { return $block->setFieldVisibility('report_type', '0'); }, array(0 => 'content', 1 => 'product.report.grid.container')), false);
$this->addItemRelation($item, 'grid.filter.form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'product.report.grid.container');