<?php $this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('page/1column.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_info', 'as' => 'info', 'name' => 'sales.order.info'), 'sales.order.info', 'content', array()), false);
$this->addItemRelation($item, 'sales.order.info');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_info_buttons', 'as' => 'buttons', 'name' => 'sales.order.info.buttons'), 'sales.order.info.buttons', 'sales.order.info', array(0 => 'content')), false);
$this->addItemRelation($item, 'sales.order.info.buttons');
$this->addItemRelation($item, 'sales.order.info');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_invoice', 'name' => 'sales.order.invoice'), 'sales.order.invoice', 'content', array()), false);
$this->addItemRelation($item, 'sales.order.invoice');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_invoice_items', 'name' => 'invoice_items', 'template' => 'sales/order/invoice/items.phtml'), 'invoice_items', 'sales.order.invoice', array(0 => 'content')), false);
$this->addItemRelation($item, 'invoice_items');
$this->addItemRelation($item, 'sales.order.invoice');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'invoice_items', function ($block) { return $block->addItemRender('default', 'sales/order_item_renderer_default', 'sales/order/invoice/items/renderer/default.phtml'); }, array(0 => 'content', 1 => 'sales.order.invoice')), false);
$this->addItemRelation($item, 'invoice_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.invoice');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'invoice_items', function ($block) { return $block->addItemRender('grouped', 'sales/order_item_renderer_grouped', 'sales/order/invoice/items/renderer/default.phtml'); }, array(0 => 'content', 1 => 'sales.order.invoice')), false);
$this->addItemRelation($item, 'invoice_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.invoice');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_invoice_totals', 'name' => 'invoice_totals', 'template' => 'sales/order/totals.phtml'), 'invoice_totals', 'invoice_items', array(0 => 'content', 1 => 'sales.order.invoice')), false);
$this->addItemRelation($item, 'invoice_totals');
$this->addItemRelation($item, 'invoice_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.invoice');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setLabelProperties'), 'invoice_totals', function ($block) { return $block->setLabelProperties('colspan="4" class="a-right"'); }, array(0 => 'content', 1 => 'sales.order.invoice', 2 => 'invoice_items')), false);
$this->addItemRelation($item, 'invoice_totals');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.invoice');
$this->addItemRelation($item, 'invoice_items');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setValueProperties'), 'invoice_totals', function ($block) { return $block->setValueProperties('class="last a-right"'); }, array(0 => 'content', 1 => 'sales.order.invoice', 2 => 'invoice_items')), false);
$this->addItemRelation($item, 'invoice_totals');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.invoice');
$this->addItemRelation($item, 'invoice_items');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'tax/sales_order_tax', 'name' => 'tax', 'template' => 'tax/order/tax.phtml'), 'tax', 'invoice_totals', array(0 => 'content', 1 => 'sales.order.invoice', 2 => 'invoice_items')), false);
$this->addItemRelation($item, 'tax');
$this->addItemRelation($item, 'invoice_totals');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.invoice');
$this->addItemRelation($item, 'invoice_items');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_comments', 'name' => 'invoice_comments', 'template' => 'sales/order/comments.phtml'), 'invoice_comments', 'invoice_items', array(0 => 'content', 1 => 'sales.order.invoice')), false);
$this->addItemRelation($item, 'invoice_comments');
$this->addItemRelation($item, 'invoice_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.invoice');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addLink', 'translate' => 'label', 'module' => 'sales'), 'sales.order.info', function ($block) { return $block->addLink('view', '*/*/view', Mage::helper('sales')->__('Order Information')); }, array()), false);
$this->addItemRelation($item, 'sales.order.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addLink', 'translate' => 'label', 'module' => 'sales'), 'sales.order.info', function ($block) { return $block->addLink('invoice', '', Mage::helper('sales')->__('Invoices')); }, array()), false);
$this->addItemRelation($item, 'sales.order.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addLink', 'translate' => 'label', 'module' => 'sales'), 'sales.order.info', function ($block) { return $block->addLink('shipment', '*/*/shipment', Mage::helper('sales')->__('Shipments')); }, array()), false);
$this->addItemRelation($item, 'sales.order.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addLink', 'translate' => 'label', 'module' => 'sales'), 'sales.order.info', function ($block) { return $block->addLink('creditmemo', '*/*/creditmemo', Mage::helper('sales')->__('Refunds')); }, array()), false);
$this->addItemRelation($item, 'sales.order.info');