<?php $this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('page/2columns-right.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('varien/product.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('varien/configurable.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'review/product_view', 'name' => 'product.info', 'template' => 'catalog/product/view.phtml'), 'product.info', 'content', array()), false);
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'catalog/product_view_media', 'name' => 'product.info.media', 'as' => 'media', 'template' => 'catalog/product/view/media.phtml'), 'product.info.media', 'product.info', array(0 => 'content')), false);
$this->addItemRelation($item, 'product.info.media');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'disableGallery'), 'product.info.media', function ($block) { return $block->disableGallery(); }, array(0 => 'content', 1 => 'product.info')), false);
$this->addItemRelation($item, 'product.info.media');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'product.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'catalog/product_view', 'name' => 'product.info.addto', 'as' => 'addto', 'template' => 'catalog/product/view/addto.phtml'), 'product.info.addto', 'product.info', array(0 => 'content')), false);
$this->addItemRelation($item, 'product.info.addto');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'catalog/product_view', 'name' => 'product.info.addtocart', 'as' => 'addtocart', 'template' => 'catalog/product/view/addtocart.phtml'), 'product.info.addtocart', 'product.info', array(0 => 'content')), false);
$this->addItemRelation($item, 'product.info.addtocart');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/html_wrapper', 'name' => 'review.product.info.addtocart.paypal.wrapper', 'translate' => 'label', 'module' => 'paypal'), 'review.product.info.addtocart.paypal.wrapper', 'product.info.addtocart', array(0 => 'content', 1 => 'product.info')), false);
$this->addItemRelation($item, 'review.product.info.addtocart.paypal.wrapper');
$this->addItemRelation($item, 'product.info.addtocart');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'product.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'paypal/express_shortcut', 'name' => 'review.product.info.addtocart.paypal', 'template' => 'paypal/express/product/shortcut.phtml'), 'review.product.info.addtocart.paypal', 'review.product.info.addtocart.paypal.wrapper', array(0 => 'content', 1 => 'product.info', 2 => 'product.info.addtocart')), false);
$this->addItemRelation($item, 'review.product.info.addtocart.paypal');
$this->addItemRelation($item, 'review.product.info.addtocart.paypal.wrapper');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'product.info.addtocart');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setIsInCatalogProduct'), 'review.product.info.addtocart.paypal', function ($block) { return $block->setIsInCatalogProduct('1'); }, array(0 => 'content', 1 => 'product.info', 2 => 'product.info.addtocart', 3 => 'review.product.info.addtocart.paypal.wrapper')), false);
$this->addItemRelation($item, 'review.product.info.addtocart.paypal');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'product.info.addtocart');
$this->addItemRelation($item, 'review.product.info.addtocart.paypal.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'catalog/product_view', 'name' => 'product.tierprices', 'as' => 'tierprices', 'template' => 'catalog/product/view/tierprices.phtml'), 'product.tierprices', 'product.info', array(0 => 'content')), false);
$this->addItemRelation($item, 'product.tierprices');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/template', 'name' => 'product.info.other', 'as' => 'other', 'template' => 'review/product/view/other.phtml'), 'product.info.other', 'product.info', array(0 => 'content')), false);
$this->addItemRelation($item, 'product.info.other');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/html_pager', 'name' => 'product_review_list.toolbar'), 'product_review_list.toolbar', 'product.info', array(0 => 'content')), false);
$this->addItemRelation($item, 'product_review_list.toolbar');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/template', 'name' => 'product_review_list.count', 'template' => 'review/product/view/count.phtml'), 'product_review_list.count', 'product.info', array(0 => 'content')), false);
$this->addItemRelation($item, 'product_review_list.count');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'review/product_view_list', 'name' => 'product.info.product_additional_data', 'as' => 'product_additional_data', 'template' => 'review/product/view/list.phtml'), 'product.info.product_additional_data', 'product.info', array(0 => 'content')), false);
$this->addItemRelation($item, 'product.info.product_additional_data');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'review/form', 'name' => 'product.review.form', 'as' => 'review_form'), 'product.review.form', 'product.info.product_additional_data', array(0 => 'content', 1 => 'product.info')), false);
$this->addItemRelation($item, 'product.review.form');
$this->addItemRelation($item, 'product.info.product_additional_data');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'product.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/html_wrapper', 'name' => 'product.review.form.fields.before', 'as' => 'form_fields_before', 'translate' => 'label'), 'product.review.form.fields.before', 'product.review.form', array(0 => 'content', 1 => 'product.info', 2 => 'product.info.product_additional_data')), false);
$this->addItemRelation($item, 'product.review.form.fields.before');
$this->addItemRelation($item, 'product.review.form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'product.info.product_additional_data');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setMayBeInvisible'), 'product.review.form.fields.before', function ($block) { return $block->setMayBeInvisible('1'); }, array(0 => 'content', 1 => 'product.info', 2 => 'product.info.product_additional_data', 3 => 'product.review.form')), false);
$this->addItemRelation($item, 'product.review.form.fields.before');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'product.info');
$this->addItemRelation($item, 'product.info.product_additional_data');
$this->addItemRelation($item, 'product.review.form');