<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_creditmemo_view', 'name' => 'sales_creditmemo_view'), 'sales_creditmemo_view', 'content', array()), false);
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_creditmemo_view_form', 'name' => 'form', 'template' => 'sales/order/creditmemo/view/form.phtml'), 'form', 'sales_creditmemo_view', array(0 => 'content')), false);
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_view_info', 'name' => 'order_info', 'template' => 'sales/order/view/info.phtml'), 'order_info', 'form', array(0 => 'content', 1 => 'sales_creditmemo_view')), false);
$this->addItemRelation($item, 'order_info');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_payment', 'name' => 'order_payment'), 'order_payment', 'form', array(0 => 'content', 1 => 'sales_creditmemo_view')), false);
$this->addItemRelation($item, 'order_payment');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_creditmemo_view_items', 'name' => 'creditmemo_items', 'template' => 'sales/order/creditmemo/view/items.phtml'), 'creditmemo_items', 'form', array(0 => 'content', 1 => 'sales_creditmemo_view')), false);
$this->addItemRelation($item, 'creditmemo_items');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'creditmemo_items', function ($block) { return $block->addItemRender('default', 'adminhtml/sales_items_renderer_default', 'sales/order/creditmemo/view/items/renderer/default.phtml'); }, array(0 => 'content', 1 => 'sales_creditmemo_view', 2 => 'form')), false);
$this->addItemRelation($item, 'creditmemo_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addColumnRender'), 'creditmemo_items', function ($block) { return $block->addColumnRender('qty', 'adminhtml/sales_items_column_qty', 'sales/items/column/qty.phtml'); }, array(0 => 'content', 1 => 'sales_creditmemo_view', 2 => 'form')), false);
$this->addItemRelation($item, 'creditmemo_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addColumnRender'), 'creditmemo_items', function ($block) { return $block->addColumnRender('name', 'adminhtml/sales_items_column_name', 'sales/items/column/name.phtml'); }, array(0 => 'content', 1 => 'sales_creditmemo_view', 2 => 'form')), false);
$this->addItemRelation($item, 'creditmemo_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addColumnRender'), 'creditmemo_items', function ($block) { return $block->addColumnRender('name', 'adminhtml/sales_items_column_name_grouped', 'sales/items/column/name.phtml', 'grouped'); }, array(0 => 'content', 1 => 'sales_creditmemo_view', 2 => 'form')), false);
$this->addItemRelation($item, 'creditmemo_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'order_item_extra_info'), 'order_item_extra_info', 'creditmemo_items', array(0 => 'content', 1 => 'sales_creditmemo_view', 2 => 'form')), false);
$this->addItemRelation($item, 'order_item_extra_info');
$this->addItemRelation($item, 'creditmemo_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_comments_view', 'name' => 'order_comments', 'template' => 'sales/order/comments/view.phtml'), 'order_comments', 'form', array(0 => 'content', 1 => 'sales_creditmemo_view')), false);
$this->addItemRelation($item, 'order_comments');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setParentType'), 'order_comments', function ($block) { return $block->setParentType('creditmemo'); }, array(0 => 'content', 1 => 'sales_creditmemo_view', 2 => 'form')), false);
$this->addItemRelation($item, 'order_comments');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_creditmemo_totals', 'name' => 'creditmemo_totals', 'template' => 'sales/order/totals.phtml'), 'creditmemo_totals', 'form', array(0 => 'content', 1 => 'sales_creditmemo_view')), false);
$this->addItemRelation($item, 'creditmemo_totals');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_totals_tax', 'name' => 'tax', 'template' => 'sales/order/totals/tax.phtml'), 'tax', 'creditmemo_totals', array(0 => 'content', 1 => 'sales_creditmemo_view', 2 => 'form')), false);
$this->addItemRelation($item, 'tax');
$this->addItemRelation($item, 'creditmemo_totals');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_creditmemo_view');
$this->addItemRelation($item, 'form');