<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'connect/adminhtml_extension_custom_edit', 'name' => 'connect_extension_edit'), 'connect_extension_edit', 'content', array()), false);
$this->addItemRelation($item, 'connect_extension_edit');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'connect/adminhtml_extension_custom_edit_tabs', 'name' => 'connect_extension_edit_tabs'), 'connect_extension_edit_tabs', 'left', array()), false);
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'connect/adminhtml_extension_custom_edit_tab_package', 'name' => 'tab_package', 'template' => 'connect/extension/custom/package.phtml'), 'tab_package', 'connect_extension_edit_tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'tab_package');
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'connect/adminhtml_extension_custom_edit_tab_release', 'name' => 'tab_release', 'template' => 'connect/extension/custom/release.phtml'), 'tab_release', 'connect_extension_edit_tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'tab_release');
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'connect/adminhtml_extension_custom_edit_tab_authors', 'name' => 'tab_authors', 'template' => 'connect/extension/custom/authors.phtml'), 'tab_authors', 'connect_extension_edit_tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'tab_authors');
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'connect/adminhtml_extension_custom_edit_tab_depends', 'name' => 'tab_depends', 'template' => 'connect/extension/custom/depends.phtml'), 'tab_depends', 'connect_extension_edit_tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'tab_depends');
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'connect/adminhtml_extension_custom_edit_tab_contents', 'name' => 'tab_contents', 'template' => 'connect/extension/custom/contents.phtml'), 'tab_contents', 'connect_extension_edit_tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'tab_contents');
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'connect/adminhtml_extension_custom_edit_tab_local', 'name' => 'tab_local'), 'tab_local', 'connect_extension_edit_tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'tab_local');
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'connect_extension_edit_tabs', function ($block) { return $block->addTab('package_info', 'tab_package'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'connect_extension_edit_tabs', function ($block) { return $block->addTab('release_info', 'tab_release'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'connect_extension_edit_tabs', function ($block) { return $block->addTab('authors', 'tab_authors'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'connect_extension_edit_tabs', function ($block) { return $block->addTab('dependencies', 'tab_depends'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'connect_extension_edit_tabs', function ($block) { return $block->addTab('contents', 'tab_contents'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'connect_extension_edit_tabs', function ($block) { return $block->addTab('load_local_package', 'tab_local'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'connect_extension_edit_tabs');
$this->addItemRelation($item, 'left');