<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('right'));
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('left'));
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('page/1column.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'paypal/express_review', 'name' => 'paypal.express.review', 'template' => 'paypal/express/review.phtml'), 'paypal.express.review', 'content', array()), false);
$this->addItemRelation($item, 'paypal.express.review');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'paypal/express_review', 'name' => 'express.review.shipping.method', 'as' => 'shipping_method', 'template' => 'paypal/express/review/shipping/method.phtml'), 'express.review.shipping.method', 'paypal.express.review', array(0 => 'content')), false);
$this->addItemRelation($item, 'express.review.shipping.method');
$this->addItemRelation($item, 'paypal.express.review');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'paypal/express_review_details', 'name' => 'paypal.express.review.details', 'as' => 'details', 'template' => 'paypal/express/review/details.phtml'), 'paypal.express.review.details', 'paypal.express.review', array(0 => 'content')), false);
$this->addItemRelation($item, 'paypal.express.review.details');
$this->addItemRelation($item, 'paypal.express.review');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'paypal.express.review.details', function ($block) { return $block->addItemRender('default', 'checkout/cart_item_renderer', 'checkout/onepage/review/item.phtml'); }, array(0 => 'content', 1 => 'paypal.express.review')), false);
$this->addItemRelation($item, 'paypal.express.review.details');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'paypal.express.review');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'paypal.express.review.details', function ($block) { return $block->addItemRender('grouped', 'checkout/cart_item_renderer_grouped', 'checkout/onepage/review/item.phtml'); }, array(0 => 'content', 1 => 'paypal.express.review')), false);
$this->addItemRelation($item, 'paypal.express.review.details');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'paypal.express.review');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'paypal.express.review.details', function ($block) { return $block->addItemRender('configurable', 'checkout/cart_item_renderer_configurable', 'checkout/onepage/review/item.phtml'); }, array(0 => 'content', 1 => 'paypal.express.review')), false);
$this->addItemRelation($item, 'paypal.express.review.details');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'paypal.express.review');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/cart_totals', 'name' => 'paypal.express.review.details.totals', 'as' => 'totals', 'template' => 'checkout/onepage/review/totals.phtml'), 'paypal.express.review.details.totals', 'paypal.express.review.details', array(0 => 'content', 1 => 'paypal.express.review')), false);
$this->addItemRelation($item, 'paypal.express.review.details.totals');
$this->addItemRelation($item, 'paypal.express.review.details');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'paypal.express.review');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/agreements', 'name' => 'paypal.express.review.details.agreements', 'as' => 'agreements', 'template' => 'checkout/onepage/agreements.phtml'), 'paypal.express.review.details.agreements', 'paypal.express.review', array(0 => 'content')), false);
$this->addItemRelation($item, 'paypal.express.review.details.agreements');
$this->addItemRelation($item, 'paypal.express.review');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('skin_js', 'js/checkout/review.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'additional.product.info'), 'additional.product.info', null, array()), false);
$this->addItemRelation($item, 'additional.product.info');
$this->addItemRelation($item, NULL);