<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/store_switcher', 'name' => 'store_switcher', 'template' => 'store/switcher.phtml'), 'store_switcher', 'left', array()), false);
$this->addItemRelation($item, 'store_switcher');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/catalog_product_edit_action_attribute_tabs', 'name' => 'attributes_tabs'), 'attributes_tabs', 'left', array()), false);
$this->addItemRelation($item, 'attributes_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/catalog_product_edit_action_attribute_tab_attributes', 'name' => 'tab_attributes'), 'tab_attributes', 'attributes_tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'tab_attributes');
$this->addItemRelation($item, 'attributes_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/catalog_product_edit_action_attribute_tab_inventory', 'name' => 'tab_inventory', 'template' => 'catalog/product/edit/action/inventory.phtml'), 'tab_inventory', 'attributes_tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'tab_inventory');
$this->addItemRelation($item, 'attributes_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/catalog_product_edit_action_attribute_tab_websites', 'name' => 'tab_websites', 'template' => 'catalog/product/edit/action/websites.phtml'), 'tab_websites', 'attributes_tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'tab_websites');
$this->addItemRelation($item, 'attributes_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'attributes_tabs', function ($block) { return $block->addTab('attributes', 'tab_attributes'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'attributes_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'attributes_tabs', function ($block) { return $block->addTab('inventory', 'tab_inventory'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'attributes_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'attributes_tabs', function ($block) { return $block->addTab('websites', 'tab_websites'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'attributes_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/catalog_product_edit_action_attribute', 'name' => 'attribute', 'template' => 'catalog/product/edit/action/attribute.phtml'), 'attribute', 'content', array()), false);
$this->addItemRelation($item, 'attribute');
$this->addItemRelation($item, 'content');