<?php $this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('empty.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'scriptaculous/controls.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'prototype/window.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'scriptaculous/builder.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'scriptaculous/dragdrop.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'scriptaculous/controls.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'scriptaculous/slider.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'lib/ccard.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'varien/js.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'mage/adminhtml/hash.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'mage/adminhtml/events.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'mage/adminhtml/loader.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'mage/adminhtml/grid.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'mage/adminhtml/tabs.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'mage/adminhtml/accordion.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'mage/adminhtml/uploader.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'mage/adminhtml/product.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'mage/adminhtml/rules.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'mage/adminhtml/wysiwyg/tiny_mce/setup.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'lib/ds-sleight.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'varien/iehover-fix.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('css', 'print.css'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js_css', 'calendar/calendar-win2k-1.css'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js_css', 'extjs/resources/css/ext-all.css'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js_css', 'extjs/resources/css/ytheme-magento.css'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('skin_css', 'menu.css'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'calendar/calendar.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'calendar/calendar-setup.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'extjs/fix-defer-before.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'extjs/ext-tree.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'extjs/fix-defer.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'removeItem'), 'head', function ($block) { return $block->removeItem('js', 'extjs/ext-tree-checkbox.js'); }, array()), false);
$this->addItemRelation($item, 'head');