<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Include('checkout_multishipping'));
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/multishipping_overview', 'name' => 'checkout_overview', 'template' => 'checkout/multishipping/overview.phtml'), 'checkout_overview', 'content', array()), false);
$this->addItemRelation($item, 'checkout_overview');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'checkout_overview', function ($block) { return $block->addItemRender('default', 'checkout/cart_item_renderer', 'checkout/multishipping/item/default.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout_overview');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'checkout_overview', function ($block) { return $block->addItemRender('grouped', 'checkout/cart_item_renderer_grouped', 'checkout/multishipping/item/default.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout_overview');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'checkout_overview', function ($block) { return $block->addItemRender('configurable', 'checkout/cart_item_renderer_configurable', 'checkout/multishipping/item/default.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout_overview');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addRowItemRender'), 'checkout_overview', function ($block) { return $block->addRowItemRender('grouped', 'checkout/cart_item_renderer_grouped', 'checkout/multishipping/overview/item.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout_overview');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addRowItemRender'), 'checkout_overview', function ($block) { return $block->addRowItemRender('configurable', 'checkout/cart_item_renderer_configurable', 'checkout/multishipping/overview/item.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout_overview');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/multishipping_payment_info', 'name' => 'payment_info'), 'payment_info', 'checkout_overview', array(0 => 'content')), false);
$this->addItemRelation($item, 'payment_info');
$this->addItemRelation($item, 'checkout_overview');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setInfoTemplate'), 'payment_info', function ($block) { return $block->setInfoTemplate('', ''); }, array(0 => 'content', 1 => 'checkout_overview')), false);
$this->addItemRelation($item, 'payment_info');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout_overview');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/agreements', 'name' => 'checkout.multishipping.agreements', 'as' => 'agreements', 'template' => 'checkout/multishipping/agreements.phtml'), 'checkout.multishipping.agreements', 'checkout_overview', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.multishipping.agreements');
$this->addItemRelation($item, 'checkout_overview');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/cart_totals', 'name' => 'totals'), 'totals', 'checkout_overview', array(0 => 'content')), false);
$this->addItemRelation($item, 'totals');
$this->addItemRelation($item, 'checkout_overview');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'checkout.multishipping.overview.items.after', 'as' => 'items_after', 'translate' => 'label'), 'checkout.multishipping.overview.items.after', 'checkout_overview', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.multishipping.overview.items.after');
$this->addItemRelation($item, 'checkout_overview');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'additional.product.info', 'translate' => 'label'), 'additional.product.info', null, array()), false);
$this->addItemRelation($item, 'additional.product.info');
$this->addItemRelation($item, NULL);