<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'catalog/product_view_type_grouped', 'name' => 'product.info.grouped', 'as' => 'product_type_data', 'template' => 'catalog/product/view/type/grouped.phtml'), 'product.info.grouped', 'product.info', array()), false);
$this->addItemRelation($item, 'product.info.grouped');
$this->addItemRelation($item, 'product.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'product.info.grouped.extra', 'as' => 'product_type_data_extra', 'translate' => 'label'), 'product.info.grouped.extra', 'product.info.grouped', array(0 => 'product.info')), false);
$this->addItemRelation($item, 'product.info.grouped.extra');
$this->addItemRelation($item, 'product.info.grouped');
$this->addItemRelation($item, 'product.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'catalog/product_view_type_grouped', 'name' => 'product.info.availability', 'as' => 'product_type_availability', 'template' => 'catalog/product/view/type/availability/grouped.phtml'), 'product.info.availability', 'product.info', array()), false);
$this->addItemRelation($item, 'product.info.availability');
$this->addItemRelation($item, 'product.info');