<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_print', 'name' => 'sales.order.print', 'template' => 'sales/order/print.phtml'), 'sales.order.print', 'content', array()), false);
$this->addItemRelation($item, 'sales.order.print');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'sales.order.print', function ($block) { return $block->addItemRender('default', 'sales/order_item_renderer_default', 'sales/order/items/renderer/default.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'sales.order.print');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'sales.order.print', function ($block) { return $block->addItemRender('grouped', 'sales/order_item_renderer_grouped', 'sales/order/items/renderer/default.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'sales.order.print');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_totals', 'name' => 'order_totals', 'template' => 'sales/order/totals.phtml'), 'order_totals', 'sales.order.print', array(0 => 'content')), false);
$this->addItemRelation($item, 'order_totals');
$this->addItemRelation($item, 'sales.order.print');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setLabelProperties'), 'order_totals', function ($block) { return $block->setLabelProperties('colspan="4" class="a-right"'); }, array(0 => 'content', 1 => 'sales.order.print')), false);
$this->addItemRelation($item, 'order_totals');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.print');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setValueProperties'), 'order_totals', function ($block) { return $block->setValueProperties('class="last a-right"'); }, array(0 => 'content', 1 => 'sales.order.print')), false);
$this->addItemRelation($item, 'order_totals');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.print');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'tax/sales_order_tax', 'name' => 'tax', 'template' => 'tax/order/tax.phtml'), 'tax', 'order_totals', array(0 => 'content', 1 => 'sales.order.print')), false);
$this->addItemRelation($item, 'tax');
$this->addItemRelation($item, 'order_totals');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.print');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setIsPlaneMode'), 'tax', function ($block) { return $block->setIsPlaneMode('1'); }, array(0 => 'content', 1 => 'sales.order.print', 2 => 'order_totals')), false);
$this->addItemRelation($item, 'tax');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.print');
$this->addItemRelation($item, 'order_totals');