<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('right'));
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('left'));
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('page/1column.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/template_container', 'name' => 'seo.sitemap.container', 'template' => 'catalog/seo/sitemap/container.phtml'), 'seo.sitemap.container', 'content', array()), false);
$this->addItemRelation($item, 'seo.sitemap.container');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/template_links', 'name' => 'seo.sitemap.links', 'as' => 'links', 'template' => 'page/template/links.phtml'), 'seo.sitemap.links', 'seo.sitemap.container', array(0 => 'content')), false);
$this->addItemRelation($item, 'seo.sitemap.links');
$this->addItemRelation($item, 'seo.sitemap.container');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/html_pager', 'name' => 'seo.sitemap.pager.top', 'as' => 'pager_top', 'template' => 'page/html/pager.phtml'), 'seo.sitemap.pager.top', 'seo.sitemap.container', array(0 => 'content')), false);
$this->addItemRelation($item, 'seo.sitemap.pager.top');
$this->addItemRelation($item, 'seo.sitemap.container');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/html_pager', 'name' => 'seo.sitemap.pager.bottom', 'as' => 'pager_bottom', 'template' => 'page/html/pager.phtml'), 'seo.sitemap.pager.bottom', 'seo.sitemap.container', array(0 => 'content')), false);
$this->addItemRelation($item, 'seo.sitemap.pager.bottom');
$this->addItemRelation($item, 'seo.sitemap.container');
$this->addItemRelation($item, 'content');