<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'form.additional.info'), 'form.additional.info', 'checkout.onepage.login', array()), false);
$this->addItemRelation($item, 'form.additional.info');
$this->addItemRelation($item, 'checkout.onepage.login');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'captcha/captcha', 'name' => 'captcha'), 'captcha', 'form.additional.info', array(0 => 'checkout.onepage.login')), false);
$this->addItemRelation($item, 'captcha');
$this->addItemRelation($item, 'form.additional.info');
$this->addItemRelation($item, 'checkout.onepage.login');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/captcha.js'); }, array(0 => 'checkout.onepage.login', 1 => 'form.additional.info', 2 => 'captcha')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'checkout.onepage.login');
$this->addItemRelation($item, 'form.additional.info');
$this->addItemRelation($item, 'captcha');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setFormId'), 'captcha', function ($block) { return $block->setFormId('user_login'); }, array(0 => 'checkout.onepage.login', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha');
$this->addItemRelation($item, 'checkout.onepage.login');
$this->addItemRelation($item, 'form.additional.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setImgWidth'), 'captcha', function ($block) { return $block->setImgWidth('230'); }, array(0 => 'checkout.onepage.login', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha');
$this->addItemRelation($item, 'checkout.onepage.login');
$this->addItemRelation($item, 'form.additional.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setImgHeight'), 'captcha', function ($block) { return $block->setImgHeight('50'); }, array(0 => 'checkout.onepage.login', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha');
$this->addItemRelation($item, 'checkout.onepage.login');
$this->addItemRelation($item, 'form.additional.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'form.additional.info'), 'form.additional.info', 'checkout.onepage.billing', array()), false);
$this->addItemRelation($item, 'form.additional.info');
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'captcha/captcha', 'name' => 'captcha.guest.checkout'), 'captcha.guest.checkout', 'form.additional.info', array(0 => 'checkout.onepage.billing')), false);
$this->addItemRelation($item, 'captcha.guest.checkout');
$this->addItemRelation($item, 'form.additional.info');
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/captcha.js'); }, array(0 => 'checkout.onepage.billing', 1 => 'form.additional.info', 2 => 'captcha.guest.checkout')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItemRelation($item, 'form.additional.info');
$this->addItemRelation($item, 'captcha.guest.checkout');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setFormId'), 'captcha.guest.checkout', function ($block) { return $block->setFormId('guest_checkout'); }, array(0 => 'checkout.onepage.billing', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha.guest.checkout');
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItemRelation($item, 'form.additional.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setImgWidth'), 'captcha.guest.checkout', function ($block) { return $block->setImgWidth('230'); }, array(0 => 'checkout.onepage.billing', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha.guest.checkout');
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItemRelation($item, 'form.additional.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setImgHeight'), 'captcha.guest.checkout', function ($block) { return $block->setImgHeight('50'); }, array(0 => 'checkout.onepage.billing', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha.guest.checkout');
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItemRelation($item, 'form.additional.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'captcha/captcha', 'name' => 'captcha.register.during.checkout'), 'captcha.register.during.checkout', 'form.additional.info', array(0 => 'checkout.onepage.billing')), false);
$this->addItemRelation($item, 'captcha.register.during.checkout');
$this->addItemRelation($item, 'form.additional.info');
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/captcha.js'); }, array(0 => 'checkout.onepage.billing', 1 => 'form.additional.info', 2 => 'captcha.register.during.checkout')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItemRelation($item, 'form.additional.info');
$this->addItemRelation($item, 'captcha.register.during.checkout');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setFormId'), 'captcha.register.during.checkout', function ($block) { return $block->setFormId('register_during_checkout'); }, array(0 => 'checkout.onepage.billing', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha.register.during.checkout');
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItemRelation($item, 'form.additional.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setImgWidth'), 'captcha.register.during.checkout', function ($block) { return $block->setImgWidth('230'); }, array(0 => 'checkout.onepage.billing', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha.register.during.checkout');
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItemRelation($item, 'form.additional.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setImgHeight'), 'captcha.register.during.checkout', function ($block) { return $block->setImgHeight('50'); }, array(0 => 'checkout.onepage.billing', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha.register.during.checkout');
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItemRelation($item, 'form.additional.info');