<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/adminhtml_recurring_profile_view', 'name' => 'sales.recurring.profile.view', 'template' => 'widget/view/container.phtml'), 'sales.recurring.profile.view', 'content', array()), false);
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setDestElementId'), 'sales.recurring.profile.view', function ($block) { return $block->setDestElementId('sales_recurring_profile_view'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/widget_tabs', 'name' => 'sales.recurring.profile.view.tabs'), 'sales.recurring.profile.view.tabs', 'left', array()), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setDestElementId'), 'sales.recurring.profile.view.tabs', function ($block) { return $block->setDestElementId('sales_recurring_profile_view'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTitle', 'translate' => 'value'), 'sales.recurring.profile.view.tabs', function ($block) { return $block->setTitle(Mage::helper('core')->__('Recurring Profile View')); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setId'), 'sales.recurring.profile.view.tabs', function ($block) { return $block->setId('sales_recurring_profile_view_tabs'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/adminhtml_recurring_profile_view_tab_info', 'as' => 'info_tab', 'name' => 'sales.recurring.profile.tab.info', 'template' => 'sales/recurring/profile/view.phtml'), 'sales.recurring.profile.tab.info', 'sales.recurring.profile.view.tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.general', 'as' => 'general', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.general', 'sales.recurring.profile.tab.info', array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.general');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareReferenceInfo'), 'sales.recurring.profile.view.general', function ($block) { return $block->prepareReferenceInfo(); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.general');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.general', function ($block) { return $block->addToParentGroup('info_blocks_row_1'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.general');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.general', function ($block) { return $block->setViewColumn('1'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.general');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.general', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Reference')); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.general');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.item', 'as' => 'item', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.item', 'sales.recurring.profile.tab.info', array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.item');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareItemInfo'), 'sales.recurring.profile.view.item', function ($block) { return $block->prepareItemInfo(); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.item');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.item', function ($block) { return $block->addToParentGroup('info_blocks_row_1'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.item');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.item', function ($block) { return $block->setViewColumn('2'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.item');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.item', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Purchased Item')); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.item');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.schedule', 'as' => 'profile', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.schedule', 'sales.recurring.profile.tab.info', array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.schedule');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareScheduleInfo'), 'sales.recurring.profile.view.schedule', function ($block) { return $block->prepareScheduleInfo(); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.schedule');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.schedule', function ($block) { return $block->addToParentGroup('info_blocks_row_2'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.schedule');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.schedule', function ($block) { return $block->setViewColumn('1'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.schedule');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.schedule', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Profile Schedule')); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.schedule');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.fees', 'as' => 'fees', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.fees', 'sales.recurring.profile.tab.info', array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.fees');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareFeesInfo'), 'sales.recurring.profile.view.fees', function ($block) { return $block->prepareFeesInfo(); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.fees');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.fees', function ($block) { return $block->addToParentGroup('info_blocks_row_2'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.fees');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.fees', function ($block) { return $block->setViewColumn('2'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.fees');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.fees', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Profile Payments')); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.fees');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.billing', 'as' => 'billing_address', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.billing', 'sales.recurring.profile.tab.info', array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.billing');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareAddressInfo'), 'sales.recurring.profile.view.billing', function ($block) { return $block->prepareAddressInfo(); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.billing');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.billing', function ($block) { return $block->addToParentGroup('info_blocks_row_3'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.billing');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.billing', function ($block) { return $block->setViewColumn('1'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.billing');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.billing', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Billing Address')); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.billing');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.shipping', 'as' => 'shipping_address', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.shipping', 'sales.recurring.profile.tab.info', array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setAddressType'), 'sales.recurring.profile.view.shipping', function ($block) { return $block->setAddressType('shipping'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareAddressInfo'), 'sales.recurring.profile.view.shipping', function ($block) { return $block->prepareAddressInfo(); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.shipping', function ($block) { return $block->addToParentGroup('info_blocks_row_3'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.shipping', function ($block) { return $block->setViewColumn('2'); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.shipping', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Shipping Address')); }, array(0 => 'left', 1 => 'sales.recurring.profile.view.tabs', 2 => 'sales.recurring.profile.tab.info')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'sales.recurring.profile.tab.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/adminhtml_recurring_profile_view_tab_orders', 'as' => 'orders_tab', 'name' => 'sales.recurring.profile.tab.orders'), 'sales.recurring.profile.tab.orders', 'sales.recurring.profile.view.tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'sales.recurring.profile.tab.orders');
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'sales.recurring.profile.view.tabs', function ($block) { return $block->addTab('recurring_profile_info', 'info_tab'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'sales.recurring.profile.view.tabs', function ($block) { return $block->addTab('recurring_profile_orders', 'orders_tab'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tabs');
$this->addItemRelation($item, 'left');