<?php $this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/sales/packaging.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_shipment_view', 'name' => 'sales_shipment_view'), 'sales_shipment_view', 'content', array()), false);
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_shipment_view_form', 'name' => 'form', 'template' => 'sales/order/shipment/view/form.phtml'), 'form', 'sales_shipment_view', array(0 => 'content')), false);
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_view_info', 'name' => 'order_info', 'template' => 'sales/order/view/info.phtml'), 'order_info', 'form', array(0 => 'content', 1 => 'sales_shipment_view')), false);
$this->addItemRelation($item, 'order_info');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_payment', 'name' => 'order_payment'), 'order_payment', 'form', array(0 => 'content', 1 => 'sales_shipment_view')), false);
$this->addItemRelation($item, 'order_payment');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_shipment_view_tracking', 'name' => 'shipment_tracking', 'template' => 'sales/order/shipment/view/tracking.phtml'), 'shipment_tracking', 'form', array(0 => 'content', 1 => 'sales_shipment_view')), false);
$this->addItemRelation($item, 'shipment_tracking');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_shipment_view_items', 'name' => 'shipment_items', 'template' => 'sales/order/shipment/view/items.phtml'), 'shipment_items', 'form', array(0 => 'content', 1 => 'sales_shipment_view')), false);
$this->addItemRelation($item, 'shipment_items');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'shipment_items', function ($block) { return $block->addItemRender('default', 'adminhtml/sales_items_renderer_default', 'sales/order/shipment/view/items/renderer/default.phtml'); }, array(0 => 'content', 1 => 'sales_shipment_view', 2 => 'form')), false);
$this->addItemRelation($item, 'shipment_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addColumnRender'), 'shipment_items', function ($block) { return $block->addColumnRender('qty', 'adminhtml/sales_items_column_qty', 'sales/items/column/qty.phtml'); }, array(0 => 'content', 1 => 'sales_shipment_view', 2 => 'form')), false);
$this->addItemRelation($item, 'shipment_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addColumnRender'), 'shipment_items', function ($block) { return $block->addColumnRender('name', 'adminhtml/sales_items_column_name', 'sales/items/column/name.phtml'); }, array(0 => 'content', 1 => 'sales_shipment_view', 2 => 'form')), false);
$this->addItemRelation($item, 'shipment_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'order_item_extra_info'), 'order_item_extra_info', 'shipment_items', array(0 => 'content', 1 => 'sales_shipment_view', 2 => 'form')), false);
$this->addItemRelation($item, 'order_item_extra_info');
$this->addItemRelation($item, 'shipment_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_invoice_create_tracking', 'name' => 'invoice_tracking', 'template' => 'sales/order/shipment/create/tracking.phtml'), 'invoice_tracking', 'form', array(0 => 'content', 1 => 'sales_shipment_view')), false);
$this->addItemRelation($item, 'invoice_tracking');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_comments_view', 'name' => 'order_comments', 'template' => 'sales/order/comments/view.phtml'), 'order_comments', 'form', array(0 => 'content', 1 => 'sales_shipment_view')), false);
$this->addItemRelation($item, 'order_comments');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setParentType'), 'order_comments', function ($block) { return $block->setParentType('shipment'); }, array(0 => 'content', 1 => 'sales_shipment_view', 2 => 'form')), false);
$this->addItemRelation($item, 'order_comments');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_shipment_packaging', 'name' => 'shipment_packaging', 'template' => 'sales/order/shipment/packaging/popup.phtml'), 'shipment_packaging', 'form', array(0 => 'content', 1 => 'sales_shipment_view')), false);
$this->addItemRelation($item, 'shipment_packaging');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_shipment_packaging', 'name' => 'shipment_packed', 'template' => 'sales/order/shipment/packaging/packed.phtml'), 'shipment_packed', 'form', array(0 => 'content', 1 => 'sales_shipment_view')), false);
$this->addItemRelation($item, 'shipment_packed');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_view');