<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('left'));
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('page/2columns-right.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'unsetChildren'), 'right', function ($block) { return $block->unsetChildren(); }, array()), false);
$this->addItemRelation($item, 'right');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/html_wrapper', 'name' => 'checkout.progress.wrapper', 'translate' => 'label'), 'checkout.progress.wrapper', 'right', array()), false);
$this->addItemRelation($item, 'checkout.progress.wrapper');
$this->addItemRelation($item, 'right');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setElementId'), 'checkout.progress.wrapper', function ($block) { return $block->setElementId('checkout-progress-wrapper'); }, array(0 => 'right')), false);
$this->addItemRelation($item, 'checkout.progress.wrapper');
$this->addItemRelation($item, 'right');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_progress', 'name' => 'checkout.progress', 'before' => '-', 'template' => 'checkout/onepage/progress.phtml'), 'checkout.progress', 'checkout.progress.wrapper', array(0 => 'right')), false);
$this->addItemRelation($item, 'checkout.progress');
$this->addItemRelation($item, 'checkout.progress.wrapper');
$this->addItemRelation($item, 'right');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_progress', 'name' => 'billing.progress', 'template' => 'checkout/onepage/progress/billing.phtml'), 'billing.progress', 'checkout.progress', array(0 => 'right', 1 => 'checkout.progress.wrapper')), false);
$this->addItemRelation($item, 'billing.progress');
$this->addItemRelation($item, 'checkout.progress');
$this->addItemRelation($item, 'right');
$this->addItemRelation($item, 'checkout.progress.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_progress', 'name' => 'shipping.progress', 'template' => 'checkout/onepage/progress/shipping.phtml'), 'shipping.progress', 'checkout.progress', array(0 => 'right', 1 => 'checkout.progress.wrapper')), false);
$this->addItemRelation($item, 'shipping.progress');
$this->addItemRelation($item, 'checkout.progress');
$this->addItemRelation($item, 'right');
$this->addItemRelation($item, 'checkout.progress.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_progress', 'name' => 'shippingmethod.progress', 'template' => 'checkout/onepage/progress/shipping_method.phtml'), 'shippingmethod.progress', 'checkout.progress', array(0 => 'right', 1 => 'checkout.progress.wrapper')), false);
$this->addItemRelation($item, 'shippingmethod.progress');
$this->addItemRelation($item, 'checkout.progress');
$this->addItemRelation($item, 'right');
$this->addItemRelation($item, 'checkout.progress.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_progress', 'name' => 'payment.progress', 'template' => 'checkout/onepage/progress/payment.phtml'), 'payment.progress', 'checkout.progress', array(0 => 'right', 1 => 'checkout.progress.wrapper')), false);
$this->addItemRelation($item, 'payment.progress');
$this->addItemRelation($item, 'checkout.progress');
$this->addItemRelation($item, 'right');
$this->addItemRelation($item, 'checkout.progress.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage', 'name' => 'checkout.onepage', 'template' => 'checkout/onepage.phtml'), 'checkout.onepage', 'content', array()), false);
$this->addItemRelation($item, 'checkout.onepage');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_login', 'name' => 'checkout.onepage.login', 'as' => 'login', 'template' => 'checkout/onepage/login.phtml'), 'checkout.onepage.login', 'checkout.onepage', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.onepage.login');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/html_wrapper', 'name' => 'checkout.onepage.login.before', 'as' => 'login_before', 'translate' => 'label'), 'checkout.onepage.login.before', 'checkout.onepage.login', array(0 => 'content', 1 => 'checkout.onepage')), false);
$this->addItemRelation($item, 'checkout.onepage.login.before');
$this->addItemRelation($item, 'checkout.onepage.login');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setMayBeInvisible'), 'checkout.onepage.login.before', function ($block) { return $block->setMayBeInvisible('1'); }, array(0 => 'content', 1 => 'checkout.onepage', 2 => 'checkout.onepage.login')), false);
$this->addItemRelation($item, 'checkout.onepage.login.before');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItemRelation($item, 'checkout.onepage.login');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_billing', 'name' => 'checkout.onepage.billing', 'as' => 'billing', 'template' => 'checkout/onepage/billing.phtml'), 'checkout.onepage.billing', 'checkout.onepage', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.onepage.billing');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_shipping', 'name' => 'checkout.onepage.shipping', 'as' => 'shipping', 'template' => 'checkout/onepage/shipping.phtml'), 'checkout.onepage.shipping', 'checkout.onepage', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.onepage.shipping');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_shipping_method', 'name' => 'checkout.onepage.shipping_method', 'as' => 'shipping_method', 'template' => 'checkout/onepage/shipping_method.phtml'), 'checkout.onepage.shipping_method', 'checkout.onepage', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.onepage.shipping_method');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_shipping_method_available', 'name' => 'checkout.onepage.shipping_method.available', 'as' => 'available', 'template' => 'checkout/onepage/shipping_method/available.phtml'), 'checkout.onepage.shipping_method.available', 'checkout.onepage.shipping_method', array(0 => 'content', 1 => 'checkout.onepage')), false);
$this->addItemRelation($item, 'checkout.onepage.shipping_method.available');
$this->addItemRelation($item, 'checkout.onepage.shipping_method');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_shipping_method_additional', 'name' => 'checkout.onepage.shipping_method.additional', 'as' => 'additional', 'template' => 'checkout/onepage/shipping_method/additional.phtml'), 'checkout.onepage.shipping_method.additional', 'checkout.onepage.shipping_method', array(0 => 'content', 1 => 'checkout.onepage')), false);
$this->addItemRelation($item, 'checkout.onepage.shipping_method.additional');
$this->addItemRelation($item, 'checkout.onepage.shipping_method');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_payment', 'name' => 'checkout.onepage.payment', 'as' => 'payment', 'template' => 'checkout/onepage/payment.phtml'), 'checkout.onepage.payment', 'checkout.onepage', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.onepage.payment');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_payment_methods', 'name' => 'checkout.payment.methods', 'as' => 'methods', 'template' => 'checkout/onepage/payment/info.phtml'), 'checkout.payment.methods', 'checkout.onepage.payment', array(0 => 'content', 1 => 'checkout.onepage')), false);
$this->addItemRelation($item, 'checkout.payment.methods');
$this->addItemRelation($item, 'checkout.onepage.payment');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setMethodFormTemplate'), 'checkout.payment.methods', function ($block) { return $block->setMethodFormTemplate('purchaseorder', 'payment/form/purchaseorder.phtml'); }, array(0 => 'content', 1 => 'checkout.onepage', 2 => 'checkout.onepage.payment')), false);
$this->addItemRelation($item, 'checkout.payment.methods');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItemRelation($item, 'checkout.onepage.payment');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/template', 'name' => 'checkout.onepage.payment.additional', 'as' => 'additional'), 'checkout.onepage.payment.additional', 'checkout.onepage.payment', array(0 => 'content', 1 => 'checkout.onepage')), false);
$this->addItemRelation($item, 'checkout.onepage.payment.additional');
$this->addItemRelation($item, 'checkout.onepage.payment');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/template', 'name' => 'checkout.onepage.payment.methods_additional', 'as' => 'methods_additional'), 'checkout.onepage.payment.methods_additional', 'checkout.onepage.payment', array(0 => 'content', 1 => 'checkout.onepage')), false);
$this->addItemRelation($item, 'checkout.onepage.payment.methods_additional');
$this->addItemRelation($item, 'checkout.onepage.payment');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_review', 'name' => 'checkout.onepage.review', 'as' => 'review', 'template' => 'checkout/onepage/review.phtml'), 'checkout.onepage.review', 'checkout.onepage', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.onepage.review');
$this->addItemRelation($item, 'checkout.onepage');
$this->addItemRelation($item, 'content');