<?php $this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('page/2columns-left.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addBodyClass'), 'root', function ($block) { return $block->addBodyClass('customer-account'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/html_wrapper', 'name' => 'my.account.wrapper', 'translate' => 'label'), 'my.account.wrapper', 'content', array()), false);
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setElementClass'), 'my.account.wrapper', function ($block) { return $block->setElementClass('my-account'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'customer/account_navigation', 'name' => 'customer_account_navigation', 'before' => '-', 'template' => 'customer/account/navigation.phtml'), 'customer_account_navigation', 'left_first', array()), false);
$this->addItemRelation($item, 'customer_account_navigation');
$this->addItemRelation($item, 'left_first');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addLink', 'translate' => 'label', 'module' => 'customer'), 'customer_account_navigation', function ($block) { return $block->addLink('account', 'customer/account/', Mage::helper('customer')->__('Account Dashboard')); }, array(0 => 'left_first')), false);
$this->addItemRelation($item, 'customer_account_navigation');
$this->addItemRelation($item, 'left_first');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addLink', 'translate' => 'label', 'module' => 'customer'), 'customer_account_navigation', function ($block) { return $block->addLink('account_edit', 'customer/account/edit/', Mage::helper('customer')->__('Account Information')); }, array(0 => 'left_first')), false);
$this->addItemRelation($item, 'customer_account_navigation');
$this->addItemRelation($item, 'left_first');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addLink', 'translate' => 'label', 'module' => 'customer'), 'customer_account_navigation', function ($block) { return $block->addLink('address_book', 'customer/address/', Mage::helper('customer')->__('Address Book')); }, array(0 => 'left_first')), false);
$this->addItemRelation($item, 'customer_account_navigation');
$this->addItemRelation($item, 'left_first');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'catalog/product_compare_sidebar', 'name' => 'catalog.compare.sidebar', 'template' => 'catalog/product/compare/sidebar.phtml'), 'catalog.compare.sidebar', 'left', array()), false);
$this->addItemRelation($item, 'catalog.compare.sidebar');
$this->addItemRelation($item, 'left');
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('tags_popular'));