<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'form.additional.info'), 'form.additional.info', 'customer_form_login', array()), false);
$this->addItemRelation($item, 'form.additional.info');
$this->addItemRelation($item, 'customer_form_login');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'captcha/captcha', 'name' => 'captcha'), 'captcha', 'form.additional.info', array(0 => 'customer_form_login')), false);
$this->addItemRelation($item, 'captcha');
$this->addItemRelation($item, 'form.additional.info');
$this->addItemRelation($item, 'customer_form_login');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/captcha.js'); }, array(0 => 'customer_form_login', 1 => 'form.additional.info', 2 => 'captcha')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'customer_form_login');
$this->addItemRelation($item, 'form.additional.info');
$this->addItemRelation($item, 'captcha');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setFormId'), 'captcha', function ($block) { return $block->setFormId('user_login'); }, array(0 => 'customer_form_login', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha');
$this->addItemRelation($item, 'customer_form_login');
$this->addItemRelation($item, 'form.additional.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setImgWidth'), 'captcha', function ($block) { return $block->setImgWidth('230'); }, array(0 => 'customer_form_login', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha');
$this->addItemRelation($item, 'customer_form_login');
$this->addItemRelation($item, 'form.additional.info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setImgHeight'), 'captcha', function ($block) { return $block->setImgHeight('50'); }, array(0 => 'customer_form_login', 1 => 'form.additional.info')), false);
$this->addItemRelation($item, 'captcha');
$this->addItemRelation($item, 'customer_form_login');
$this->addItemRelation($item, 'form.additional.info');