<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Include('customer_account'));
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('page/2columns-left.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'customer/account_dashboard', 'name' => 'customer_account_dashboard', 'template' => 'customer/account/dashboard.phtml'), 'customer_account_dashboard', 'my.account.wrapper', array()), false);
$this->addItemRelation($item, 'customer_account_dashboard');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'customer/account_dashboard_hello', 'name' => 'customer_account_dashboard_hello', 'as' => 'hello', 'template' => 'customer/account/dashboard/hello.phtml'), 'customer_account_dashboard_hello', 'customer_account_dashboard', array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'customer_account_dashboard_hello');
$this->addItemRelation($item, 'customer_account_dashboard');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/template', 'name' => 'customer_account_dashboard_top', 'as' => 'top'), 'customer_account_dashboard_top', 'customer_account_dashboard', array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'customer_account_dashboard_top');
$this->addItemRelation($item, 'customer_account_dashboard');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'customer/account_dashboard_info', 'name' => 'customer_account_dashboard_info', 'as' => 'info', 'template' => 'customer/account/dashboard/info.phtml'), 'customer_account_dashboard_info', 'customer_account_dashboard', array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'customer_account_dashboard_info');
$this->addItemRelation($item, 'customer_account_dashboard');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'customer/account_dashboard_newsletter', 'name' => 'customer_account_dashboard_newsletter', 'as' => 'newsletter', 'template' => 'customer/account/dashboard/newsletter.phtml'), 'customer_account_dashboard_newsletter', 'customer_account_dashboard', array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'customer_account_dashboard_newsletter');
$this->addItemRelation($item, 'customer_account_dashboard');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'customer/account_dashboard_address', 'name' => 'customer_account_dashboard_address', 'as' => 'address', 'template' => 'customer/account/dashboard/address.phtml'), 'customer_account_dashboard_address', 'customer_account_dashboard', array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'customer_account_dashboard_address');
$this->addItemRelation($item, 'customer_account_dashboard');
$this->addItemRelation($item, 'my.account.wrapper');