<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('footer'));
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('head'));
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('name' => 'wysiwyg_images.js', 'type' => 'adminhtml/cms_wysiwyg_images_content', 'template' => 'cms/browser/js.phtml'), 'wysiwyg_images.js', 'left', array()), false);
$this->addItemRelation($item, 'wysiwyg_images.js');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('name' => 'wysiwyg_images.tree', 'type' => 'adminhtml/cms_wysiwyg_images_tree', 'template' => 'cms/browser/tree.phtml'), 'wysiwyg_images.tree', 'left', array()), false);
$this->addItemRelation($item, 'wysiwyg_images.tree');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('name' => 'wysiwyg_images.content', 'type' => 'adminhtml/cms_wysiwyg_images_content', 'template' => 'cms/browser/content.phtml'), 'wysiwyg_images.content', 'content', array()), false);
$this->addItemRelation($item, 'wysiwyg_images.content');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('name' => 'wysiwyg_images.uploader', 'type' => 'adminhtml/cms_wysiwyg_images_content_uploader', 'template' => 'cms/browser/content/uploader.phtml'), 'wysiwyg_images.uploader', 'wysiwyg_images.content', array(0 => 'content')), false);
$this->addItemRelation($item, 'wysiwyg_images.uploader');
$this->addItemRelation($item, 'wysiwyg_images.content');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('name' => 'wysiwyg_images.newfolder', 'type' => 'adminhtml/cms_wysiwyg_images_content_newfolder', 'template' => 'cms/browser/content/newfolder.phtml'), 'wysiwyg_images.newfolder', 'wysiwyg_images.content', array(0 => 'content')), false);
$this->addItemRelation($item, 'wysiwyg_images.newfolder');
$this->addItemRelation($item, 'wysiwyg_images.content');
$this->addItemRelation($item, 'content');