<?php $this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/sales/packaging.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_shipment_create', 'name' => 'sales_shipment_create'), 'sales_shipment_create', 'content', array()), false);
$this->addItemRelation($item, 'sales_shipment_create');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_shipment_create_form', 'name' => 'form', 'template' => 'sales/order/shipment/create/form.phtml'), 'form', 'sales_shipment_create', array(0 => 'content')), false);
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'sales_shipment_create');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_view_info', 'name' => 'order_info', 'template' => 'sales/order/view/info.phtml'), 'order_info', 'form', array(0 => 'content', 1 => 'sales_shipment_create')), false);
$this->addItemRelation($item, 'order_info');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_create');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_payment', 'name' => 'order_payment'), 'order_payment', 'form', array(0 => 'content', 1 => 'sales_shipment_create')), false);
$this->addItemRelation($item, 'order_payment');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_create');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_shipment_create_tracking', 'name' => 'shipment_tracking', 'template' => 'sales/order/shipment/create/tracking.phtml'), 'shipment_tracking', 'form', array(0 => 'content', 1 => 'sales_shipment_create')), false);
$this->addItemRelation($item, 'shipment_tracking');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_create');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_shipment_create_items', 'name' => 'order_items', 'template' => 'sales/order/shipment/create/items.phtml'), 'order_items', 'form', array(0 => 'content', 1 => 'sales_shipment_create')), false);
$this->addItemRelation($item, 'order_items');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_create');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'order_items', function ($block) { return $block->addItemRender('default', 'adminhtml/sales_items_renderer_default', 'sales/order/shipment/create/items/renderer/default.phtml'); }, array(0 => 'content', 1 => 'sales_shipment_create', 2 => 'form')), false);
$this->addItemRelation($item, 'order_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_create');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addColumnRender'), 'order_items', function ($block) { return $block->addColumnRender('qty', 'adminhtml/sales_items_column_qty', 'sales/items/column/qty.phtml'); }, array(0 => 'content', 1 => 'sales_shipment_create', 2 => 'form')), false);
$this->addItemRelation($item, 'order_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_create');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addColumnRender'), 'order_items', function ($block) { return $block->addColumnRender('name', 'adminhtml/sales_items_column_name', 'sales/items/column/name.phtml'); }, array(0 => 'content', 1 => 'sales_shipment_create', 2 => 'form')), false);
$this->addItemRelation($item, 'order_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_create');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'order_item_extra_info'), 'order_item_extra_info', 'order_items', array(0 => 'content', 1 => 'sales_shipment_create', 2 => 'form')), false);
$this->addItemRelation($item, 'order_item_extra_info');
$this->addItemRelation($item, 'order_items');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_create');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_shipment_packaging', 'name' => 'shipment_packaging', 'template' => 'sales/order/shipment/packaging/popup.phtml'), 'shipment_packaging', 'form', array(0 => 'content', 1 => 'sales_shipment_create')), false);
$this->addItemRelation($item, 'shipment_packaging');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales_shipment_create');