<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'tag/product_result', 'name' => 'tag_products', 'template' => 'catalogsearch/result.phtml'), 'tag_products', 'content', array()), false);
$this->addItemRelation($item, 'tag_products');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'catalog/product_list', 'name' => 'search_result_list', 'template' => 'catalog/product/list.phtml'), 'search_result_list', 'tag_products', array(0 => 'content')), false);
$this->addItemRelation($item, 'search_result_list');
$this->addItemRelation($item, 'tag_products');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'catalog/product_list_toolbar', 'name' => 'product_list_toolbar', 'template' => 'catalog/product/list/toolbar.phtml'), 'product_list_toolbar', 'search_result_list', array(0 => 'content', 1 => 'tag_products')), false);
$this->addItemRelation($item, 'product_list_toolbar');
$this->addItemRelation($item, 'search_result_list');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'tag_products');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/html_pager', 'name' => 'product_list_toolbar_pager'), 'product_list_toolbar_pager', 'product_list_toolbar', array(0 => 'content', 1 => 'tag_products', 2 => 'search_result_list')), false);
$this->addItemRelation($item, 'product_list_toolbar_pager');
$this->addItemRelation($item, 'product_list_toolbar');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'tag_products');
$this->addItemRelation($item, 'search_result_list');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setToolbarBlockName'), 'search_result_list', function ($block) { return $block->setToolbarBlockName('product_list_toolbar'); }, array(0 => 'content', 1 => 'tag_products')), false);
$this->addItemRelation($item, 'search_result_list');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'tag_products');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setListOrders'), 'tag_products', function ($block) { return $block->setListOrders(); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'tag_products');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setListModes'), 'tag_products', function ($block) { return $block->setListModes(); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'tag_products');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setListCollection'), 'tag_products', function ($block) { return $block->setListCollection(); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'tag_products');
$this->addItemRelation($item, 'content');