<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/page', 'name' => 'root', 'output' => 'toHtml', 'template' => 'page.phtml'), 'root', null, array()), false);
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, NULL);
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/page_head', 'name' => 'head', 'as' => 'head', 'template' => 'page/head.phtml'), 'head', 'root', array()), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTitle', 'translate' => 'title'), 'head', function ($block) { return $block->setTitle(Mage::helper('core')->__('Magento Admin')); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('prototype/prototype.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js', 'extjs/fix-defer-before.js', '', '', 'can_load_ext_js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('prototype/window.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('scriptaculous/builder.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('scriptaculous/effects.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('scriptaculous/dragdrop.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('scriptaculous/controls.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('scriptaculous/slider.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('lib/ccard.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('prototype/validation.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('varien/js.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/translate.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/hash.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/events.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/loader.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/grid.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/tabs.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/form.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/accordion.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/tools.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/uploader.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/product.js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addCss'), 'head', function ($block) { return $block->addCss('reset.css'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addCss'), 'head', function ($block) { return $block->addCss('boxes.css'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addCss'), 'head', function ($block) { return $block->addCss('custom.css'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('skin_css', 'iestyles.css', '', 'lt IE 8'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('skin_css', 'below_ie7.css', '', 'lt IE 7'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('skin_css', 'ie7.css', '', 'IE 7'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addCss'), 'head', function ($block) { return $block->addCss('print.css', 'media="print"'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js', 'lib/ds-sleight.js', 'defer', 'lt IE 7'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js', 'varien/iehover-fix.js', '', 'lt IE 7'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('skin_css', 'menu.css', 'media="screen, projection"'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js_css', 'calendar/calendar-win2k-1.css', '', ''); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js', 'calendar/calendar.js', ''); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js', 'calendar/calendar-setup.js', ''); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js', 'extjs/ext-tree.js', '', '', 'can_load_ext_js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js', 'extjs/fix-defer.js', '', '', 'can_load_ext_js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js', 'extjs/ext-tree-checkbox.js', '', '', 'can_load_ext_js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js_css', 'extjs/resources/css/ext-all.css', '', '', 'can_load_ext_js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js_css', 'extjs/resources/css/ytheme-magento.css', '', '', 'can_load_ext_js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js', 'mage/adminhtml/rules.js', '', '', 'can_load_rules_js'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItem'), 'head', function ($block) { return $block->addItem('js', 'mage/adminhtml/wysiwyg/tiny_mce/setup.js', '', '', 'can_load_tiny_mce'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/html_calendar', 'name' => 'head.calendar', 'as' => 'calendar', 'template' => 'page/js/calendar.phtml'), 'head.calendar', 'head', array(0 => 'root')), false);
$this->addItemRelation($item, 'head.calendar');
$this->addItemRelation($item, 'head');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/page_notices', 'name' => 'global_notices', 'as' => 'global_notices', 'template' => 'page/notices.phtml'), 'global_notices', 'root', array()), false);
$this->addItemRelation($item, 'global_notices');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/page_header', 'name' => 'header', 'as' => 'header'), 'header', 'root', array()), false);
$this->addItemRelation($item, 'header');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/page_menu', 'name' => 'menu', 'as' => 'menu'), 'menu', 'root', array()), false);
$this->addItemRelation($item, 'menu');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'notifications', 'as' => 'notifications'), 'notifications', 'root', array()), false);
$this->addItemRelation($item, 'notifications');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/notification_baseurl', 'name' => 'notification_baseurl', 'as' => 'notification_baseurl', 'template' => 'notification/baseurl.phtml'), 'notification_baseurl', 'notifications', array(0 => 'root')), false);
$this->addItemRelation($item, 'notification_baseurl');
$this->addItemRelation($item, 'notifications');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/cache_notifications', 'name' => 'cache_notifications', 'template' => 'system/cache/notifications.phtml'), 'cache_notifications', 'notifications', array(0 => 'root')), false);
$this->addItemRelation($item, 'cache_notifications');
$this->addItemRelation($item, 'notifications');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/notification_survey', 'name' => 'notification_survey', 'template' => 'notification/survey.phtml'), 'notification_survey', 'notifications', array(0 => 'root')), false);
$this->addItemRelation($item, 'notification_survey');
$this->addItemRelation($item, 'notifications');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/notification_security', 'name' => 'notification_security', 'as' => 'notification_security', 'template' => 'notification/security.phtml'), 'notification_security', 'notifications', array(0 => 'root')), false);
$this->addItemRelation($item, 'notification_security');
$this->addItemRelation($item, 'notifications');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/widget_breadcrumbs', 'name' => 'breadcrumbs', 'as' => 'breadcrumbs'), 'breadcrumbs', 'root', array()), false);
$this->addItemRelation($item, 'breadcrumbs');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/template', 'name' => 'formkey', 'as' => 'formkey', 'template' => 'formkey.phtml'), 'formkey', 'root', array()), false);
$this->addItemRelation($item, 'formkey');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/js_translate', 'name' => 'js_translate', 'as' => 'js_translate', 'template' => 'page/js/translate.phtml'), 'js_translate', 'root', array()), false);
$this->addItemRelation($item, 'js_translate');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'left', 'as' => 'left'), 'left', 'root', array()), false);
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'content', 'as' => 'content'), 'content', 'root', array()), false);
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/messages', 'name' => 'messages', 'as' => 'messages'), 'messages', 'root', array()), false);
$this->addItemRelation($item, 'messages');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'js', 'as' => 'js'), 'js', 'root', array()), false);
$this->addItemRelation($item, 'js');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/page_footer', 'name' => 'footer', 'as' => 'footer'), 'footer', 'root', array()), false);
$this->addItemRelation($item, 'footer');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setBugreportUrl'), 'footer', function ($block) { return $block->setBugreportUrl('http://www.magentocommerce.com/bug-tracking'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'footer');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setConnectWithMagentoUrl'), 'footer', function ($block) { return $block->setConnectWithMagentoUrl('http://magento.com/resources/technical'); }, array(0 => 'root')), false);
$this->addItemRelation($item, 'footer');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/profiler', 'name' => 'profiler', 'as' => 'profiler'), 'profiler', 'root', array()), false);
$this->addItemRelation($item, 'profiler');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'before_body_end', 'as' => 'before_body_end'), 'before_body_end', 'root', array()), false);
$this->addItemRelation($item, 'before_body_end');
$this->addItemRelation($item, 'root');