<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Include('customer_account'));
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Include('sales_recurring_profile_view__tabs'));
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setIsViewCurrent'), 'sales.recurring.profile.view.tab.profile', function ($block) { return $block->setIsViewCurrent('1'); }, array()), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tab.profile');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.general', 'as' => 'general', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.general', 'sales.recurring.profile.view', array()), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.general');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareReferenceInfo'), 'sales.recurring.profile.view.general', function ($block) { return $block->prepareReferenceInfo(); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.general');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.general', function ($block) { return $block->addToParentGroup('info_blocks_row_1'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.general');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.general', function ($block) { return $block->setViewColumn('1'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.general');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.general', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Reference')); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.general');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.item', 'as' => 'item', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.item', 'sales.recurring.profile.view', array()), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.item');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareItemInfo'), 'sales.recurring.profile.view.item', function ($block) { return $block->prepareItemInfo(); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.item');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.item', function ($block) { return $block->addToParentGroup('info_blocks_row_1'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.item');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.item', function ($block) { return $block->setViewColumn('2'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.item');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.item', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Purchased Item')); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.item');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.schedule', 'as' => 'profile', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.schedule', 'sales.recurring.profile.view', array()), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.schedule');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareScheduleInfo'), 'sales.recurring.profile.view.schedule', function ($block) { return $block->prepareScheduleInfo(); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.schedule');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.schedule', function ($block) { return $block->addToParentGroup('info_blocks_row_2'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.schedule');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.schedule', function ($block) { return $block->setViewColumn('1'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.schedule');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.schedule', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Profile Schedule')); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.schedule');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.fees', 'as' => 'fees', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.fees', 'sales.recurring.profile.view', array()), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.fees');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareFeesInfo'), 'sales.recurring.profile.view.fees', function ($block) { return $block->prepareFeesInfo(); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.fees');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.fees', function ($block) { return $block->addToParentGroup('info_blocks_row_2'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.fees');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.fees', function ($block) { return $block->setViewColumn('2'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.fees');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.fees', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Profile Payments')); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.fees');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.billing', 'as' => 'billing_address', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.billing', 'sales.recurring.profile.view', array()), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.billing');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareAddressInfo'), 'sales.recurring.profile.view.billing', function ($block) { return $block->prepareAddressInfo(); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.billing');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.billing', function ($block) { return $block->addToParentGroup('info_blocks_row_3'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.billing');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.billing', function ($block) { return $block->setViewColumn('1'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.billing');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.billing', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Billing Address')); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.billing');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view.shipping', 'as' => 'shipping_address', 'template' => 'sales/recurring/profile/view/info.phtml'), 'sales.recurring.profile.view.shipping', 'sales.recurring.profile.view', array()), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setAddressType'), 'sales.recurring.profile.view.shipping', function ($block) { return $block->setAddressType('shipping'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareAddressInfo'), 'sales.recurring.profile.view.shipping', function ($block) { return $block->prepareAddressInfo(); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.shipping', function ($block) { return $block->addToParentGroup('info_blocks_row_3'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewColumn'), 'sales.recurring.profile.view.shipping', function ($block) { return $block->setViewColumn('2'); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.shipping', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Shipping Address')); }, array(0 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.shipping');
$this->addItemRelation($item, 'sales.recurring.profile.view');