<?php $this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('page/2columns-left.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profile_view', 'name' => 'sales.recurring.profile.view', 'template' => 'sales/recurring/profile/view.phtml'), 'sales.recurring.profile.view', 'my.account.wrapper', array()), false);
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareViewData'), 'sales.recurring.profile.view', function ($block) { return $block->prepareViewData(); }, array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setShouldPrepareInfoTabs'), 'sales.recurring.profile.view', function ($block) { return $block->setShouldPrepareInfoTabs('1'); }, array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text', 'as' => 'profile_info', 'name' => 'sales.recurring.profile.view.tab.profile'), 'sales.recurring.profile.view.tab.profile', 'sales.recurring.profile.view', array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tab.profile');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.tab.profile', function ($block) { return $block->addToParentGroup('info_tabs'); }, array(0 => 'my.account.wrapper', 1 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tab.profile');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.tab.profile', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Profile Information')); }, array(0 => 'my.account.wrapper', 1 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tab.profile');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewAction'), 'sales.recurring.profile.view.tab.profile', function ($block) { return $block->setViewAction('view'); }, array(0 => 'my.account.wrapper', 1 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tab.profile');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text', 'as' => 'related_orders', 'name' => 'sales.recurring.profile.view.tab.orders'), 'sales.recurring.profile.view.tab.orders', 'sales.recurring.profile.view', array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tab.orders');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addToParentGroup'), 'sales.recurring.profile.view.tab.orders', function ($block) { return $block->addToParentGroup('info_tabs'); }, array(0 => 'my.account.wrapper', 1 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tab.orders');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewLabel', 'translate' => 'value'), 'sales.recurring.profile.view.tab.orders', function ($block) { return $block->setViewLabel(Mage::helper('core')->__('Related Orders')); }, array(0 => 'my.account.wrapper', 1 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tab.orders');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.recurring.profile.view');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setViewAction'), 'sales.recurring.profile.view.tab.orders', function ($block) { return $block->setViewAction('orders'); }, array(0 => 'my.account.wrapper', 1 => 'sales.recurring.profile.view')), false);
$this->addItemRelation($item, 'sales.recurring.profile.view.tab.orders');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.recurring.profile.view');