<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_print_invoice', 'name' => 'sales.order.print.invoice', 'template' => 'sales/order/print/invoice.phtml'), 'sales.order.print.invoice', 'content', array()), false);
$this->addItemRelation($item, 'sales.order.print.invoice');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'sales.order.print.invoice', function ($block) { return $block->addItemRender('default', 'sales/order_item_renderer_default', 'sales/order/invoice/items/renderer/default.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'sales.order.print.invoice');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'sales.order.print.invoice', function ($block) { return $block->addItemRender('grouped', 'sales/order_item_renderer_grouped', 'sales/order/invoice/items/renderer/default.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'sales.order.print.invoice');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/order_invoice_totals', 'name' => 'invoice_totals', 'template' => 'sales/order/totals.phtml'), 'invoice_totals', 'sales.order.print.invoice', array(0 => 'content')), false);
$this->addItemRelation($item, 'invoice_totals');
$this->addItemRelation($item, 'sales.order.print.invoice');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setLabelProperties'), 'invoice_totals', function ($block) { return $block->setLabelProperties('colspan="4" class="a-right"'); }, array(0 => 'content', 1 => 'sales.order.print.invoice')), false);
$this->addItemRelation($item, 'invoice_totals');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.print.invoice');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setValueProperties'), 'invoice_totals', function ($block) { return $block->setValueProperties('class="last a-right"'); }, array(0 => 'content', 1 => 'sales.order.print.invoice')), false);
$this->addItemRelation($item, 'invoice_totals');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.print.invoice');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'tax/sales_order_tax', 'name' => 'tax', 'template' => 'tax/order/tax.phtml'), 'tax', 'invoice_totals', array(0 => 'content', 1 => 'sales.order.print.invoice')), false);
$this->addItemRelation($item, 'tax');
$this->addItemRelation($item, 'invoice_totals');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.print.invoice');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setIsPlaneMode'), 'tax', function ($block) { return $block->setIsPlaneMode('1'); }, array(0 => 'content', 1 => 'sales.order.print.invoice', 2 => 'invoice_totals')), false);
$this->addItemRelation($item, 'tax');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'sales.order.print.invoice');
$this->addItemRelation($item, 'invoice_totals');