<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('right'));
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('left'));
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_review_info', 'name' => 'root', 'output' => 'toHtml', 'template' => 'checkout/onepage/review/info.phtml'), 'root', null, array()), false);
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, NULL);
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'root', function ($block) { return $block->addItemRender('default', 'checkout/cart_item_renderer', 'checkout/onepage/review/item.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'root', function ($block) { return $block->addItemRender('grouped', 'checkout/cart_item_renderer_grouped', 'checkout/onepage/review/item.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'root', function ($block) { return $block->addItemRender('configurable', 'checkout/cart_item_renderer_configurable', 'checkout/onepage/review/item.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/cart_totals', 'name' => 'checkout.onepage.review.info.totals', 'as' => 'totals', 'template' => 'checkout/onepage/review/totals.phtml'), 'checkout.onepage.review.info.totals', 'root', array()), false);
$this->addItemRelation($item, 'checkout.onepage.review.info.totals');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'checkout.onepage.review.info.items.before', 'as' => 'items_before', 'translate' => 'label'), 'checkout.onepage.review.info.items.before', 'root', array()), false);
$this->addItemRelation($item, 'checkout.onepage.review.info.items.before');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'checkout.onepage.review.info.items.after', 'as' => 'items_after', 'translate' => 'label'), 'checkout.onepage.review.info.items.after', 'root', array()), false);
$this->addItemRelation($item, 'checkout.onepage.review.info.items.after');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/agreements', 'name' => 'checkout.onepage.agreements', 'as' => 'agreements', 'template' => 'checkout/onepage/agreements.phtml'), 'checkout.onepage.agreements', 'root', array()), false);
$this->addItemRelation($item, 'checkout.onepage.agreements');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/template', 'name' => 'checkout.onepage.review.button', 'as' => 'button', 'template' => 'checkout/onepage/review/button.phtml'), 'checkout.onepage.review.button', 'root', array()), false);
$this->addItemRelation($item, 'checkout.onepage.review.button');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'additional.product.info', 'translate' => 'label'), 'additional.product.info', null, array()), false);
$this->addItemRelation($item, 'additional.product.info');
$this->addItemRelation($item, NULL);