<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_items', 'template' => 'sales/order/create/items.phtml', 'name' => 'items'), 'items', 'content', array()), false);
$this->addItemRelation($item, 'items');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_items_grid', 'template' => 'sales/order/create/items/grid.phtml', 'name' => 'items_grid'), 'items_grid', 'items', array(0 => 'content')), false);
$this->addItemRelation($item, 'items_grid');
$this->addItemRelation($item, 'items');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_coupons', 'template' => 'sales/order/create/coupons/form.phtml', 'name' => 'coupons'), 'coupons', 'items_grid', array(0 => 'content', 1 => 'items')), false);
$this->addItemRelation($item, 'coupons');
$this->addItemRelation($item, 'items_grid');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'items');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_coupons_form', 'template' => 'sales/order/create/coupons/form.phtml', 'name' => 'form'), 'form', 'coupons', array(0 => 'content', 1 => 'items', 2 => 'items_grid')), false);
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'coupons');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'items');
$this->addItemRelation($item, 'items_grid');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'order_item_extra_info'), 'order_item_extra_info', 'content', array()), false);
$this->addItemRelation($item, 'order_item_extra_info');
$this->addItemRelation($item, 'content');