<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('right'));
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('left'));
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_progress', 'name' => 'root', 'output' => 'toHtml', 'template' => 'checkout/onepage/progress.phtml'), 'root', null, array()), false);
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, NULL);
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setInfoTemplate'), 'root', function ($block) { return $block->setInfoTemplate('', ''); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_progress', 'name' => 'billing.progress', 'template' => 'checkout/onepage/progress/billing.phtml'), 'billing.progress', 'root', array()), false);
$this->addItemRelation($item, 'billing.progress');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_progress', 'name' => 'shipping.progress', 'template' => 'checkout/onepage/progress/shipping.phtml'), 'shipping.progress', 'root', array()), false);
$this->addItemRelation($item, 'shipping.progress');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_progress', 'name' => 'shippingmethod.progress', 'template' => 'checkout/onepage/progress/shipping_method.phtml'), 'shippingmethod.progress', 'root', array()), false);
$this->addItemRelation($item, 'shippingmethod.progress');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_progress', 'name' => 'payment.progress', 'template' => 'checkout/onepage/progress/payment.phtml'), 'payment.progress', 'root', array()), false);
$this->addItemRelation($item, 'payment.progress');
$this->addItemRelation($item, 'root');