<?php $this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/giftmessage.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/giftoptions/tooltip.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_view', 'name' => 'sales_order_edit'), 'sales_order_edit', 'content', array()), false);
$this->addItemRelation($item, 'sales_order_edit');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_view_tabs', 'name' => 'sales_order_tabs'), 'sales_order_tabs', 'left', array()), false);
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_view_tab_info', 'name' => 'order_tab_info', 'template' => 'sales/order/view/tab/info.phtml'), 'order_tab_info', 'sales_order_tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'order_tab_info');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_view_messages', 'name' => 'order_messages'), 'order_messages', 'order_tab_info', array(0 => 'left', 1 => 'sales_order_tabs')), false);
$this->addItemRelation($item, 'order_messages');
$this->addItemRelation($item, 'order_tab_info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_view_info', 'name' => 'order_info', 'template' => 'sales/order/view/info.phtml'), 'order_info', 'order_tab_info', array(0 => 'left', 1 => 'sales_order_tabs')), false);
$this->addItemRelation($item, 'order_info');
$this->addItemRelation($item, 'order_tab_info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_view_items', 'name' => 'order_items', 'template' => 'sales/order/view/items.phtml'), 'order_items', 'order_tab_info', array(0 => 'left', 1 => 'sales_order_tabs')), false);
$this->addItemRelation($item, 'order_items');
$this->addItemRelation($item, 'order_tab_info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'order_items', function ($block) { return $block->addItemRender('default', 'adminhtml/sales_order_view_items_renderer_default', 'sales/order/view/items/renderer/default.phtml'); }, array(0 => 'left', 1 => 'sales_order_tabs', 2 => 'order_tab_info')), false);
$this->addItemRelation($item, 'order_items');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'order_tab_info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addColumnRender'), 'order_items', function ($block) { return $block->addColumnRender('qty', 'adminhtml/sales_items_column_qty', 'sales/items/column/qty.phtml'); }, array(0 => 'left', 1 => 'sales_order_tabs', 2 => 'order_tab_info')), false);
$this->addItemRelation($item, 'order_items');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'order_tab_info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addColumnRender'), 'order_items', function ($block) { return $block->addColumnRender('name', 'adminhtml/sales_items_column_name', 'sales/items/column/name.phtml'); }, array(0 => 'left', 1 => 'sales_order_tabs', 2 => 'order_tab_info')), false);
$this->addItemRelation($item, 'order_items');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'order_tab_info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addColumnRender'), 'order_items', function ($block) { return $block->addColumnRender('name', 'adminhtml/sales_items_column_name_grouped', 'sales/items/column/name.phtml', 'grouped'); }, array(0 => 'left', 1 => 'sales_order_tabs', 2 => 'order_tab_info')), false);
$this->addItemRelation($item, 'order_items');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'order_tab_info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'order_item_extra_info'), 'order_item_extra_info', 'order_items', array(0 => 'left', 1 => 'sales_order_tabs', 2 => 'order_tab_info')), false);
$this->addItemRelation($item, 'order_item_extra_info');
$this->addItemRelation($item, 'order_items');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'order_tab_info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_payment', 'name' => 'order_payment'), 'order_payment', 'order_tab_info', array(0 => 'left', 1 => 'sales_order_tabs')), false);
$this->addItemRelation($item, 'order_payment');
$this->addItemRelation($item, 'order_tab_info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_view_history', 'name' => 'order_history', 'template' => 'sales/order/view/history.phtml'), 'order_history', 'order_tab_info', array(0 => 'left', 1 => 'sales_order_tabs')), false);
$this->addItemRelation($item, 'order_history');
$this->addItemRelation($item, 'order_tab_info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/template', 'name' => 'gift_options', 'template' => 'sales/order/giftoptions.phtml'), 'gift_options', 'order_tab_info', array(0 => 'left', 1 => 'sales_order_tabs')), false);
$this->addItemRelation($item, 'gift_options');
$this->addItemRelation($item, 'order_tab_info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_view_giftmessage', 'name' => 'order_giftmessage', 'template' => 'sales/order/view/giftmessage.phtml'), 'order_giftmessage', 'gift_options', array(0 => 'left', 1 => 'sales_order_tabs', 2 => 'order_tab_info')), false);
$this->addItemRelation($item, 'order_giftmessage');
$this->addItemRelation($item, 'gift_options');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'order_tab_info');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_totals', 'name' => 'order_totals', 'template' => 'sales/order/totals.phtml'), 'order_totals', 'order_tab_info', array(0 => 'left', 1 => 'sales_order_tabs')), false);
$this->addItemRelation($item, 'order_totals');
$this->addItemRelation($item, 'order_tab_info');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_totals_tax', 'name' => 'tax', 'template' => 'sales/order/totals/tax.phtml'), 'tax', 'order_totals', array(0 => 'left', 1 => 'sales_order_tabs', 2 => 'order_tab_info')), false);
$this->addItemRelation($item, 'tax');
$this->addItemRelation($item, 'order_totals');
$this->addItemRelation($item, 'left');
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'order_tab_info');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'sales_order_tabs', function ($block) { return $block->addTab('order_info', 'order_tab_info'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'sales_order_tabs', function ($block) { return $block->addTab('order_invoices', 'adminhtml/sales_order_view_tab_invoices'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'sales_order_tabs', function ($block) { return $block->addTab('order_creditmemos', 'adminhtml/sales_order_view_tab_creditmemos'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'sales_order_tabs', function ($block) { return $block->addTab('order_shipments', 'adminhtml/sales_order_view_tab_shipments'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'sales_order_tabs', function ($block) { return $block->addTab('order_history', 'adminhtml/sales_order_view_tab_history'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'sales_order_tabs', function ($block) { return $block->addTab('order_transactions', 'adminhtml/sales_order_view_tab_transactions'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'sales_order_tabs');
$this->addItemRelation($item, 'left');