<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'api2/adminhtml_attribute_tabs', 'name' => 'api2.attribute.edit.tabs'), 'api2.attribute.edit.tabs', 'left', array()), false);
$this->addItemRelation($item, 'api2.attribute.edit.tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'api2/adminhtml_attribute_tab_resource', 'name' => 'api2.attribute.tab.resource', 'template' => 'api2/attribute/resource.phtml'), 'api2.attribute.tab.resource', 'api2.attribute.edit.tabs', array(0 => 'left')), false);
$this->addItemRelation($item, 'api2.attribute.tab.resource');
$this->addItemRelation($item, 'api2.attribute.edit.tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addTab'), 'api2.attribute.edit.tabs', function ($block) { return $block->addTab('api2_attribute_section_resources', 'api2.attribute.tab.resource'); }, array(0 => 'left')), false);
$this->addItemRelation($item, 'api2.attribute.edit.tabs');
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'api2/adminhtml_attribute_edit', 'name' => 'edit_form'), 'edit_form', 'content', array()), false);
$this->addItemRelation($item, 'edit_form');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'api2/adminhtml_attribute_edit_form', 'name' => 'form'), 'form', 'edit_form', array(0 => 'content')), false);
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'edit_form');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setCanLoadExtJs'), 'head', function ($block) { return $block->setCanLoadExtJs('1'); }, array()), false);
$this->addItemRelation($item, 'head');