<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('right'));
$this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Remove('left'));
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('page/1column.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/cart', 'name' => 'checkout.cart'), 'checkout.cart', 'content', array()), false);
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setCartTemplate'), 'checkout.cart', function ($block) { return $block->setCartTemplate('checkout/cart.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setEmptyTemplate'), 'checkout.cart', function ($block) { return $block->setEmptyTemplate('checkout/cart/noItems.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'chooseTemplate'), 'checkout.cart', function ($block) { return $block->chooseTemplate(); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'checkout.cart', function ($block) { return $block->addItemRender('simple', 'checkout/cart_item_renderer', 'checkout/cart/item/default.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'checkout.cart', function ($block) { return $block->addItemRender('grouped', 'checkout/cart_item_renderer_grouped', 'checkout/cart/item/default.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'checkout.cart', function ($block) { return $block->addItemRender('configurable', 'checkout/cart_item_renderer_configurable', 'checkout/cart/item/default.phtml'); }, array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'checkout.cart.empty.widget', 'as' => 'checkout_cart_empty_widget', 'translate' => 'label'), 'checkout.cart.empty.widget', 'checkout.cart', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart.empty.widget');
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'checkout.cart.top_methods', 'as' => 'top_methods', 'translate' => 'label'), 'checkout.cart.top_methods', 'checkout.cart', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart.top_methods');
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_link', 'name' => 'checkout.cart.methods.onepage.top', 'template' => 'checkout/onepage/link.phtml', 'after' => '-'), 'checkout.cart.methods.onepage.top', 'checkout.cart.top_methods', array(0 => 'content', 1 => 'checkout.cart')), false);
$this->addItemRelation($item, 'checkout.cart.methods.onepage.top');
$this->addItemRelation($item, 'checkout.cart.top_methods');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout.cart');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'page/html_wrapper', 'name' => 'checkout.cart.form.before', 'as' => 'form_before', 'translate' => 'label'), 'checkout.cart.form.before', 'checkout.cart', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart.form.before');
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'checkout.cart.methods', 'as' => 'methods', 'translate' => 'label'), 'checkout.cart.methods', 'checkout.cart', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart.methods');
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/onepage_link', 'name' => 'checkout.cart.methods.onepage.bottom', 'template' => 'checkout/onepage/link.phtml'), 'checkout.cart.methods.onepage.bottom', 'checkout.cart.methods', array(0 => 'content', 1 => 'checkout.cart')), false);
$this->addItemRelation($item, 'checkout.cart.methods.onepage.bottom');
$this->addItemRelation($item, 'checkout.cart.methods');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout.cart');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/multishipping_link', 'name' => 'checkout.cart.methods.multishipping', 'template' => 'checkout/multishipping/link.phtml'), 'checkout.cart.methods.multishipping', 'checkout.cart.methods', array(0 => 'content', 1 => 'checkout.cart')), false);
$this->addItemRelation($item, 'checkout.cart.methods.multishipping');
$this->addItemRelation($item, 'checkout.cart.methods');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'checkout.cart');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/cart_coupon', 'name' => 'checkout.cart.coupon', 'as' => 'coupon', 'template' => 'checkout/cart/coupon.phtml'), 'checkout.cart.coupon', 'checkout.cart', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart.coupon');
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'checkout.cart.extra', 'translate' => 'label'), 'checkout.cart.extra', 'checkout.cart', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart.extra');
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/cart_shipping', 'name' => 'checkout.cart.shipping', 'as' => 'shipping', 'template' => 'checkout/cart/shipping.phtml'), 'checkout.cart.shipping', 'checkout.cart', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart.shipping');
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'checkout.cart.widget', 'as' => 'checkout_cart_widget', 'translate' => 'label'), 'checkout.cart.widget', 'checkout.cart', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart.widget');
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/cart_crosssell', 'name' => 'checkout.cart.crosssell', 'as' => 'crosssell', 'template' => 'checkout/cart/crosssell.phtml'), 'checkout.cart.crosssell', 'checkout.cart', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart.crosssell');
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/cart_totals', 'name' => 'checkout.cart.totals', 'as' => 'totals', 'template' => 'checkout/cart/totals.phtml'), 'checkout.cart.totals', 'checkout.cart', array(0 => 'content')), false);
$this->addItemRelation($item, 'checkout.cart.totals');
$this->addItemRelation($item, 'checkout.cart');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'additional.product.info', 'translate' => 'label'), 'additional.product.info', null, array()), false);
$this->addItemRelation($item, 'additional.product.info');
$this->addItemRelation($item, NULL);