<?php $this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setIsCollapsed'), 'left', function ($block) { return $block->setIsCollapsed('true'); }, array()), false);
$this->addItemRelation($item, 'left');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/sales.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/giftmessage.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/product/composite/configure.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('varien/configurable.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addJs'), 'head', function ($block) { return $block->addJs('mage/adminhtml/giftoptions/tooltip.js'); }, array()), false);
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/template', 'name' => 'optional_zip_countries', 'as' => 'optional_zip_countries', 'template' => 'directory/js/optional_zip_countries.phtml'), 'optional_zip_countries', 'head', array()), false);
$this->addItemRelation($item, 'optional_zip_countries');
$this->addItemRelation($item, 'head');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/template', 'template' => 'sales/order/create/js.phtml', 'name' => 'create'), 'create', 'js', array()), false);
$this->addItemRelation($item, 'create');
$this->addItemRelation($item, 'js');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create', 'name' => 'content'), 'content', 'root', array()), false);
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_form', 'template' => 'sales/order/create/form.phtml', 'name' => 'form'), 'form', 'content', array(0 => 'root')), false);
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_messages', 'name' => 'message'), 'message', 'form', array(0 => 'root', 1 => 'content')), false);
$this->addItemRelation($item, 'message');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_customer', 'template' => 'sales/order/create/abstract.phtml', 'name' => 'customer'), 'customer', 'form', array(0 => 'root', 1 => 'content')), false);
$this->addItemRelation($item, 'customer');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_customer_grid', 'name' => 'grid'), 'grid', 'customer', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'grid');
$this->addItemRelation($item, 'customer');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_store', 'template' => 'sales/order/create/abstract.phtml', 'name' => 'store'), 'store', 'form', array(0 => 'root', 1 => 'content')), false);
$this->addItemRelation($item, 'store');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_store_select', 'template' => 'sales/order/create/store/select.phtml', 'name' => 'select'), 'select', 'store', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'select');
$this->addItemRelation($item, 'store');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_data', 'template' => 'sales/order/create/data.phtml', 'name' => 'data'), 'data', 'form', array(0 => 'root', 1 => 'content')), false);
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_sidebar', 'template' => 'sales/order/create/sidebar.phtml', 'name' => 'sidebar'), 'sidebar', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'sidebar');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_sidebar_cart', 'template' => 'sales/order/create/sidebar/items.phtml', 'name' => 'cart'), 'cart', 'sidebar', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'cart');
$this->addItemRelation($item, 'sidebar');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_sidebar_wishlist', 'template' => 'sales/order/create/sidebar/items.phtml', 'name' => 'wishlist'), 'wishlist', 'sidebar', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'wishlist');
$this->addItemRelation($item, 'sidebar');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_sidebar_reorder', 'template' => 'sales/order/create/sidebar/items.phtml', 'name' => 'reorder'), 'reorder', 'sidebar', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'reorder');
$this->addItemRelation($item, 'sidebar');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_sidebar_viewed', 'template' => 'sales/order/create/sidebar/items.phtml', 'name' => 'viewed'), 'viewed', 'sidebar', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'viewed');
$this->addItemRelation($item, 'sidebar');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_sidebar_compared', 'template' => 'sales/order/create/sidebar/items.phtml', 'name' => 'compared'), 'compared', 'sidebar', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'compared');
$this->addItemRelation($item, 'sidebar');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_sidebar_pcompared', 'template' => 'sales/order/create/sidebar/items.phtml', 'name' => 'pcompared'), 'pcompared', 'sidebar', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'pcompared');
$this->addItemRelation($item, 'sidebar');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_sidebar_pviewed', 'template' => 'sales/order/create/sidebar/items.phtml', 'name' => 'pviewed'), 'pviewed', 'sidebar', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'pviewed');
$this->addItemRelation($item, 'sidebar');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_form_account', 'template' => 'sales/order/create/form/account.phtml', 'name' => 'form_account'), 'form_account', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'form_account');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_shipping_address', 'template' => 'sales/order/create/form/address.phtml', 'name' => 'shipping_address'), 'shipping_address', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'shipping_address');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_billing_address', 'template' => 'sales/order/create/form/address.phtml', 'name' => 'billing_address'), 'billing_address', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'billing_address');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_shipping_method', 'template' => 'sales/order/create/abstract.phtml', 'name' => 'shipping_method'), 'shipping_method', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'shipping_method');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_shipping_method_form', 'template' => 'sales/order/create/shipping/method/form.phtml', 'name' => 'form'), 'form', 'shipping_method', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'shipping_method');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_billing_method', 'template' => 'sales/order/create/abstract.phtml', 'name' => 'billing_method'), 'billing_method', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'billing_method');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_billing_method_form', 'template' => 'sales/order/create/billing/method/form.phtml', 'name' => 'form'), 'form', 'billing_method', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'billing_method');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_newsletter', 'template' => 'sales/order/create/abstract.phtml', 'name' => 'newsletter'), 'newsletter', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'newsletter');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_newsletter_form', 'template' => 'sales/order/create/newsletter/form.phtml', 'name' => 'form'), 'form', 'newsletter', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'newsletter');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_search', 'template' => 'sales/order/create/abstract.phtml', 'name' => 'search'), 'search', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'search');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_search_grid', 'name' => 'grid'), 'grid', 'search', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'grid');
$this->addItemRelation($item, 'search');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_items', 'template' => 'sales/order/create/items.phtml', 'name' => 'items'), 'items', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'items');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_items_grid', 'template' => 'sales/order/create/items/grid.phtml', 'name' => 'items_grid'), 'items_grid', 'items', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'items_grid');
$this->addItemRelation($item, 'items');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_coupons', 'template' => 'sales/order/create/coupons/form.phtml', 'name' => 'coupons'), 'coupons', 'items_grid', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data', 4 => 'items')), false);
$this->addItemRelation($item, 'coupons');
$this->addItemRelation($item, 'items_grid');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'items');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_coupons_form', 'template' => 'sales/order/create/coupons/form.phtml', 'name' => 'form'), 'form', 'coupons', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data', 4 => 'items', 5 => 'items_grid')), false);
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'coupons');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'items');
$this->addItemRelation($item, 'items_grid');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_comment', 'template' => 'sales/order/create/comment.phtml', 'name' => 'comment'), 'comment', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'comment');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_totals', 'template' => 'sales/order/create/totals.phtml', 'name' => 'totals'), 'totals', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'totals');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/template', 'name' => 'gift_options', 'template' => 'sales/order/giftoptions.phtml'), 'gift_options', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'gift_options');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'adminhtml/sales_order_create_giftmessage', 'template' => 'sales/order/create/giftmessage.phtml', 'name' => 'giftmessage'), 'giftmessage', 'gift_options', array(0 => 'root', 1 => 'content', 2 => 'form', 3 => 'data')), false);
$this->addItemRelation($item, 'giftmessage');
$this->addItemRelation($item, 'gift_options');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');
$this->addItemRelation($item, 'data');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'order_item_extra_info'), 'order_item_extra_info', 'data', array(0 => 'root', 1 => 'content', 2 => 'form')), false);
$this->addItemRelation($item, 'order_item_extra_info');
$this->addItemRelation($item, 'data');
$this->addItemRelation($item, 'root');
$this->addItemRelation($item, 'content');
$this->addItemRelation($item, 'form');