<?php $this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/links', 'name' => 'checkout_cart_link'), 'checkout_cart_link', 'top.links', array()), false);
$this->addItemRelation($item, 'checkout_cart_link');
$this->addItemRelation($item, 'top.links');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addCartLink'), 'checkout_cart_link', function ($block) { return $block->addCartLink(); }, array(0 => 'top.links')), false);
$this->addItemRelation($item, 'checkout_cart_link');
$this->addItemRelation($item, 'top.links');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addCheckoutLink'), 'checkout_cart_link', function ($block) { return $block->addCheckoutLink(); }, array(0 => 'top.links')), false);
$this->addItemRelation($item, 'checkout_cart_link');
$this->addItemRelation($item, 'top.links');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/cart_minicart', 'name' => 'minicart_head', 'template' => 'checkout/cart/minicart.phtml', 'before' => '-'), 'minicart_head', 'header', array()), false);
$this->addItemRelation($item, 'minicart_head');
$this->addItemRelation($item, 'header');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'checkout/cart_sidebar', 'name' => 'minicart_content', 'template' => 'checkout/cart/minicart/items.phtml'), 'minicart_content', 'minicart_head', array(0 => 'header')), false);
$this->addItemRelation($item, 'minicart_content');
$this->addItemRelation($item, 'minicart_head');
$this->addItemRelation($item, 'header');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'minicart_content', function ($block) { return $block->addItemRender('default', 'checkout/cart_item_renderer', 'checkout/cart/minicart/default.phtml'); }, array(0 => 'header', 1 => 'minicart_head')), false);
$this->addItemRelation($item, 'minicart_content');
$this->addItemRelation($item, 'header');
$this->addItemRelation($item, 'minicart_head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'minicart_content', function ($block) { return $block->addItemRender('simple', 'checkout/cart_item_renderer', 'checkout/cart/minicart/default.phtml'); }, array(0 => 'header', 1 => 'minicart_head')), false);
$this->addItemRelation($item, 'minicart_content');
$this->addItemRelation($item, 'header');
$this->addItemRelation($item, 'minicart_head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'minicart_content', function ($block) { return $block->addItemRender('grouped', 'checkout/cart_item_renderer_grouped', 'checkout/cart/minicart/default.phtml'); }, array(0 => 'header', 1 => 'minicart_head')), false);
$this->addItemRelation($item, 'minicart_content');
$this->addItemRelation($item, 'header');
$this->addItemRelation($item, 'minicart_head');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'addItemRender'), 'minicart_content', function ($block) { return $block->addItemRender('configurable', 'checkout/cart_item_renderer_configurable', 'checkout/cart/minicart/default.phtml'); }, array(0 => 'header', 1 => 'minicart_head')), false);
$this->addItemRelation($item, 'minicart_content');
$this->addItemRelation($item, 'header');
$this->addItemRelation($item, 'minicart_head');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'cart_sidebar.cart_promotion', 'as' => 'cart_promotion', 'translate' => 'label', 'module' => 'checkout'), 'cart_sidebar.cart_promotion', 'minicart_content', array(0 => 'header', 1 => 'minicart_head')), false);
$this->addItemRelation($item, 'cart_sidebar.cart_promotion');
$this->addItemRelation($item, 'minicart_content');
$this->addItemRelation($item, 'header');
$this->addItemRelation($item, 'minicart_head');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'core/text_list', 'name' => 'cart_sidebar.extra_actions', 'as' => 'extra_actions', 'translate' => 'label', 'module' => 'checkout'), 'cart_sidebar.extra_actions', 'minicart_content', array(0 => 'header', 1 => 'minicart_head')), false);
$this->addItemRelation($item, 'cart_sidebar.extra_actions');
$this->addItemRelation($item, 'minicart_content');
$this->addItemRelation($item, 'header');
$this->addItemRelation($item, 'minicart_head');