<?php $this->addItem(new EcomDev_LayoutCompiler_Layout_Item_Include('customer_account'));
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setTemplate'), 'root', function ($block) { return $block->setTemplate('page/2columns-left.phtml'); }, array()), false);
$this->addItemRelation($item, 'root');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profiles', 'name' => 'sales.recurring.profiles', 'template' => 'sales/recurring/profiles.phtml'), 'sales.recurring.profiles', 'my.account.wrapper', array()), false);
$this->addItemRelation($item, 'sales.recurring.profiles');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Layout_Item_Block(array('type' => 'sales/recurring_profiles', 'name' => 'sales.recurring.profiles.grid', 'as' => 'grid', 'template' => 'sales/recurring/grid.phtml'), 'sales.recurring.profiles.grid', 'sales.recurring.profiles', array(0 => 'my.account.wrapper')), false);
$this->addItemRelation($item, 'sales.recurring.profiles.grid');
$this->addItemRelation($item, 'sales.recurring.profiles');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'prepareProfilesGrid'), 'sales.recurring.profiles.grid', function ($block) { return $block->prepareProfilesGrid(); }, array(0 => 'my.account.wrapper', 1 => 'sales.recurring.profiles')), false);
$this->addItemRelation($item, 'sales.recurring.profiles.grid');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.recurring.profiles');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setEmptyGridMessage', 'translate' => 'value'), 'sales.recurring.profiles.grid', function ($block) { return $block->setEmptyGridMessage(Mage::helper('core')->__('There are no recurring profiles yet.')); }, array(0 => 'my.account.wrapper', 1 => 'sales.recurring.profiles')), false);
$this->addItemRelation($item, 'sales.recurring.profiles.grid');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.recurring.profiles');
$this->addItem($item = new EcomDev_LayoutCompiler_Model_Layout_Item_Action(array('method' => 'setGridHtmlId'), 'sales.recurring.profiles.grid', function ($block) { return $block->setGridHtmlId('recurring_profile_list_view'); }, array(0 => 'my.account.wrapper', 1 => 'sales.recurring.profiles')), false);
$this->addItemRelation($item, 'sales.recurring.profiles.grid');
$this->addItemRelation($item, 'my.account.wrapper');
$this->addItemRelation($item, 'sales.recurring.profiles');